Content-Type: multipart/mixed; boundary="===============3443409471449293251=="
MIME-Version: 1.0
Subject: Pomodoro Session Summary

--===============3443409471449293251==
Content-Type: multipart/alternative; boundary="===============7441089610961584048=="
MIME-Version: 1.0

--===============7441089610961584048==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

U29tZSBwbGFpbiB0ZXh0

--===============7441089610961584048==
Content-Type: text/html; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office"
    style="font-family:arial, 'helvetica neue', helvetica, sans-serif">

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>


    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta name="x-apple-disable-message-reformatting">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="telephone=no" name="format-detection">
    <title>Help the Needy</title>
    <!--[if (mso 16)]><style type="text/css"> a {text-decoration: none;} </style><![endif]-->
    <!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]-->
    <!--[if gte mso 9]><xml> <o:OfficeDocumentSettings> <o:AllowPNG></o:AllowPNG> <o:PixelsPerInch>96</o:PixelsPerInch> </o:OfficeDocumentSettings> </xml><![endif]-->
    <!--[if !mso]><!-- -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:500,800&display=swap&subset=cyrillic-ext"
        rel="stylesheet">
    <!--<![endif]-->
    <style type="text/css">
        #outlook a {
            padding: 0;
        }

        .es-button {
            mso-style-priority: 100 !important;
            text-decoration: none !important;
        }

        a[x-apple-data-detectors] {
            color: inherit !important;
            text-decoration: none !important;
            font-size: inherit !important;
            font-family: inherit !important;
            font-weight: inherit !important;
            line-height: inherit !important;
        }

        .es-desk-hidden {
            display: none;
            float: left;
            overflow: hidden;
            width: 0;
            max-height: 0;
            line-height: 0;
            mso-hide: all;
        }

        [data-ogsb] .es-button {
            border-width: 0 !important;
            padding: 15px 30px 15px 30px !important;
        }

        @media only screen and (max-width:600px) {

            p,
            ul li,
            ol li,
            a {
                line-height: 150% !important
            }

            h1,
            h2,
            h3,
            h1 a,
            h2 a,
            h3 a {
                line-height: 120%
            }

            h1 {
                font-size: 30px !important;
                text-align: left
            }

            h2 {
                font-size: 24px !important;
                text-align: left
            }

            h3 {
                font-size: 20px !important;
                text-align: left
            }

            .es-header-body h1 a,
            .es-content-body h1 a,
            .es-footer-body h1 a {
                font-size: 30px !important;
                text-align: left
            }

            .es-header-body h2 a,
            .es-content-body h2 a,
            .es-footer-body h2 a {
                font-size: 24px !important;
                text-align: left
            }

            .es-header-body h3 a,
            .es-content-body h3 a,
            .es-footer-body h3 a {
                font-size: 20px !important;
                text-align: left
            }

            .es-menu td a {
                font-size: 12px !important
            }

            .es-header-body p,
            .es-header-body ul li,
            .es-header-body ol li,
            .es-header-body a {
                font-size: 14px !important
            }

            .es-content-body p,
            .es-content-body ul li,
            .es-content-body ol li,
            .es-content-body a {
                font-size: 14px !important
            }

            .es-footer-body p,
            .es-footer-body ul li,
            .es-footer-body ol li,
            .es-footer-body a {
                font-size: 12px !important
            }

            .es-infoblock p,
            .es-infoblock ul li,
            .es-infoblock ol li,
            .es-infoblock a {
                font-size: 12px !important
            }

            *[class="gmail-fix"] {
                display: none !important
            }

            .es-m-txt-c,
            .es-m-txt-c h1,
            .es-m-txt-c h2,
            .es-m-txt-c h3 {
                text-align: center !important
            }

            .es-m-txt-r,
            .es-m-txt-r h1,
            .es-m-txt-r h2,
            .es-m-txt-r h3 {
                text-align: right !important
            }

            .es-m-txt-l,
            .es-m-txt-l h1,
            .es-m-txt-l h2,
            .es-m-txt-l h3 {
                text-align: left !important
            }

            .es-m-txt-r img,
            .es-m-txt-c img,
            .es-m-txt-l img {
                display: inline !important
            }

            .es-button-border {
                display: inline-block !important
            }

            a.es-button,
            button.es-button {
                font-size: 18px !important;
                display: inline-block !important
            }

            .es-adaptive table,
            .es-left,
            .es-right {
                width: 100% !important
            }

            .es-content table,
            .es-header table,
            .es-footer table,
            .es-content,
            .es-footer,
            .es-header {
                width: 100% !important;
                max-width: 600px !important
            }

            .es-adapt-td {
                display: block !important;
                width: 100% !important
            }

            .adapt-img {
                width: 100% !important;
                height: auto !important
            }

            .es-m-p0 {
                padding: 0px !important
            }

            .es-m-p0r {
                padding-right: 0px !important
            }

            .es-m-p0l {
                padding-left: 0px !important
            }

            .es-m-p0t {
                padding-top: 0px !important
            }

            .es-m-p0b {
                padding-bottom: 0 !important
            }

            .es-m-p20b {
                padding-bottom: 20px !important
            }

            .es-mobile-hidden,
            .es-hidden {
                display: none !important
            }

            tr.es-desk-hidden,
            td.es-desk-hidden,
            table.es-desk-hidden {
                width: auto !important;
                overflow: visible !important;
                float: none !important;
                max-height: inherit !important;
                line-height: inherit !important
            }

            tr.es-desk-hidden {
                display: table-row !important
            }

            table.es-desk-hidden {
                display: table !important
            }

            td.es-desk-menu-hidden {
                display: table-cell !important
            }

            .es-menu td {
                width: 1% !important
            }

            table.es-table-not-adapt,
            .esd-block-html table {
                width: auto !important
            }

            table.es-social {
                display: inline-block !important
            }

            table.es-social td {
                display: inline-block !important
            }

            .es-desk-hidden {
                display: table-row !important;
                width: auto !important;
                overflow: visible !important;
                max-height: inherit !important
            }
        }
    </style>
    <script>
        $(document).ready(function () {
            $("button").click(function () {
                $("#div1").load("demo_test.txt", function (responseTxt, statusTxt, xhr) {
                    if (statusTxt == "success")
                        alert("External content loaded successfully!");
                    if (statusTxt == "error")
                        alert("Error: " + xhr.status + ": " + xhr.statusText);
                });
            });
        });
    </script>

</head>

<body data-new-gr-c-s-loaded="14.1086.0"
    style="width:100%;font-family:arial, 'helvetica neue', helvetica, sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0">
    <div class="es-wrapper-color" style="background-color:#BB524F">
        <!--[if gte mso 9]><v:background xmlns:v="urn:schemas-microsoft-com:vml" fill="t"> <v:fill type="tile" color="#bb524f"></v:fill> </v:background><![endif]-->


        <table class="es-wrapper" width="100%" cellspacing="0" cellpadding="0"
            style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;background-color:#BB524F">
            <tr>
                <td valign="top" style="padding:0;Margin:0">
                    <table cellpadding="0" cellspacing="0" class="es-header" align="center"
                        style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top">
                        <tr>
                            <td align="center" style="padding:0;Margin:0">

                                <table bgcolor="#cc0000" class="es-header-body" align="center" cellpadding="0"
                                    cellspacing="0"
                                    style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#cc0000;width:590px">
                                    <tr>
                                        <td align="left" style="padding:20px;Margin:0">
                                            <table cellpadding="0" cellspacing="0" width="100%"
                                                style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                <tr>
                                                    <td class="es-m-p0r" valign="top" align="center"
                                                        style="padding:0;Margin:0;width:550px">
                                                        <table cellpadding="0" cellspacing="0" width="100%"
                                                            role="presentation"
                                                            style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                            <tr>
                                                                <td align="center"
                                                                    style="padding:0;Margin:0;padding-bottom:10px;font-size:0px">
                                                                    <a target="_blank" href="https://viewstripo.email"
                                                                        style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#FFFFFF;font-size:12px"><img
                                                                            src="https://ziitdp.stripocdn.email/content/guids/CABINET_1775f2a6cbb06d146c22e78805700c18/images/screenshot_20221105_220944.jpg"
                                                                            alt="Logo"
                                                                            style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic"
                                                                            height="58" title="Logo" width="101"></a>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td style="padding:0;Margin:0">
                                                                    <table cellpadding="0" cellspacing="0" width="100%"
                                                                        class="es-menu" role="presentation"
                                                                        style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                                        <tr class="links">
                                                                            <td align="center" valign="top" width="100%"
                                                                                id="esd-menu-id-0"
                                                                                style="Margin:0;padding-left:5px;padding-right:5px;padding-top:10px;padding-bottom:10px;border:0">
                                                                                <a target="_blank"
                                                                                    href="https://viewstripo.email"
                                                                                    style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;display:block;font-family:Montserrat, 'Google Sans', 'Segoe UI', Roboto, Arial, Ubuntu, sans-serif;color:#FFFFFF;font-size:12px">Pomodoro
                                                                                    Session Summary</a>
                                                                            </td>
                                                                        </tr>
                                                                    </table>
                                                                </td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>

                    <table cellpadding="0" cellspacing="0" class="es-header" align="center"
                        style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top">
                        <tr>
                            <td align="center" style="padding:0;Margin:0">
                                <table bgcolor="#d7cbcb" class="es-header-body" align="center" cellpadding="0"
                                    cellspacing="0"
                                    style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#d7cbcb;width:590px">
                                    <tr>
                                        <td align="left"
                                            style="padding:0;Margin:0;padding-top:20px;padding-left:20px;padding-right:20px">
                                            <table cellpadding="0" cellspacing="0" width="100%"
                                                style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                <tr>
                                                    <td align="center" valign="top"
                                                        style="padding:0;Margin:0;width:550px">
                                                        <table cellpadding="0" cellspacing="0" width="100%"
                                                            role="presentation"
                                                            style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                            <tr>
                                                                <td align="left" style="padding:0;Margin:0">
                                                                    <p
                                                                        style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Montserrat, 'Google Sans', 'Segoe UI', Roboto, Arial, Ubuntu, sans-serif;line-height:18px;color:#990000;font-size:12px">
                                                                        Hello Dear!</p>
                                                                    <p
                                                                        style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Montserrat, 'Google Sans', 'Segoe UI', Roboto, Arial, Ubuntu, sans-serif;line-height:18px;color:#990000;font-size:12px">
                                                                        Hope my email finds you well</p>
                                                                    <p
                                                                        style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Montserrat, 'Google Sans', 'Segoe UI', Roboto, Arial, Ubuntu, sans-serif;line-height:18px;color:#990000;font-size:12px">
                                                                        Please find below attached summary of my Pomodoro
                                                                        session!<br>Enjoy reading :D<br><br><br></p>
                                                                </td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>

                    <table cellpadding="0" cellspacing="0" class="es-content es-visible-simple-html-only" align="center"
                        style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%">
                        <tr>
                            <td class="es-stripe-html" align="center" style="padding:0;Margin:0">
                               




                                <table bgcolor="#ffffff" class="es-content-body" align="center" cellpadding="0"
                                    cellspacing="0"
                                    style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:590px">
                                    <tr>
                                        <td align="left"
                                            style="padding:0;Margin:0;padding-top:20px;padding-left:20px;padding-right:20px">
                                            <table cellpadding="0" cellspacing="0" width="100%"
                                                style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                <tr>
                                                    <td align="center" valign="top"
                                                        style="padding:0;Margin:0;width:550px">
                                                        <table cellpadding="0" cellspacing="0" width="100%"
                                                            role="presentation"
                                                            style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                            <tr>
                                                                <td style="padding:0;Margin:0">
                                                                    <p
                                                                        style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Montserrat, 'Google Sans', 'Segoe UI', Roboto, Arial, Ubuntu, sans-serif;line-height:21px;color:#2A3C51;font-size:14px">


                                                                    </p>
                                                                </td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="left"
                                            style="Margin:0;padding-left:20px;padding-right:20px;padding-top:30px;padding-bottom:30px">
                                            <table cellpadding="0" cellspacing="0" width="100%"
                                                style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                <tr>
                                                    <td align="center" valign="top"
                                                        style="padding:0;Margin:0;width:550px">
                                                        <table cellpadding="0" cellspacing="0" width="100%"
                                                            role="presentation"
                                                            style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                            <tr>
                                                                <td align="center"
                                                                    style="padding:0;Margin:0;font-size:0px"><img
                                                                        class="adapt-img"
                                                                        src="https://ziitdp.stripocdn.email/content/guids/CABINET_1775f2a6cbb06d146c22e78805700c18/images/juicytomatohighresolutionwallpaper41024x683.jpg"
                                                                        alt
                                                                        style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic"
                                                                        width="550" height="367"></td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                    <table cellpadding="0" cellspacing="0" class="es-footer" align="center"
                        style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top">
                        <tr>
                            <td align="center" style="padding:0;Margin:0">
                                <table bgcolor="#ffffff" class="es-footer-body" align="center" cellpadding="0"
                                    cellspacing="0"
                                    style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:590px">
                                    <tr>
                                        <td align="left"
                                            style="Margin:0;padding-bottom:10px;padding-left:20px;padding-right:20px;padding-top:30px">
                                            <table cellpadding="0" cellspacing="0" width="100%"
                                                style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                <tr>
                                                    <td align="center" valign="top"
                                                        style="padding:0;Margin:0;width:550px">
                                                        <table cellpadding="0" cellspacing="0" width="100%"
                                                            role="presentation"
                                                            style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                            <tr>
                                                                <td align="center" class="es-m-txt-c"
                                                                    style="padding:0;Margin:0">
                                                                    <h1
                                                                        style="Margin:0;line-height:36px;mso-line-height-rule:exactly;font-family:Montserrat, 'Google Sans', 'Segoe UI', Roboto, Arial, Ubuntu, sans-serif;font-size:30px;font-style:normal;font-weight:bold;color:#2A3C51">
                                                                        Keep up with us</h1>
                                                                </td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="left"
                                            style="Margin:0;padding-left:20px;padding-right:20px;padding-top:25px;padding-bottom:25px">
                                            <table cellpadding="0" cellspacing="0" width="100%"
                                                style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                <tr>
                                                    <td align="center" valign="top"
                                                        style="padding:0;Margin:0;width:550px">
                                                        <table cellpadding="0" cellspacing="0" width="100%"
                                                            role="presentation"
                                                            style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                            <tr>
                                                                <td align="center" class="es-m-txt-c"
                                                                    style="padding:0;Margin:0;padding-bottom:25px">
                                                                    <h1
                                                                        style="Margin:0;line-height:36px;mso-line-height-rule:exactly;font-family:Montserrat, 'Google Sans', 'Segoe UI', Roboto, Arial, Ubuntu, sans-serif;font-size:30px;font-style:normal;font-weight:bold;color:#333333">
                                                                        Team 7&nbsp;</h1>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td align="center"
                                                                    style="padding:0;Margin:0;font-size:0">
                                                                    <table cellpadding="0" cellspacing="0"
                                                                        class="es-table-not-adapt es-social"
                                                                        role="presentation"
                                                                        style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                                        <tr>
                                                                            <td align="center" valign="top"
                                                                                style="padding:0;Margin:0"><a
                                                                                    target="_blank"
                                                                                    href="https://github.com/SefaSAHAN/TimeTrackingProject"
                                                                                    style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#2A3C51;font-size:12px"><img
                                                                                        src="https://ziitdp.stripocdn.email/content/guids/CABINET_1775f2a6cbb06d146c22e78805700c18/images/25231.png"
                                                                                        alt="Yt" title="Youtube"
                                                                                        width="32" height="32"
                                                                                        style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic"></a>
                                                                            </td>
                                                                        </tr>
                                                                    </table>
                                                                </td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="left"
                                            style="Margin:0;padding-top:20px;padding-bottom:20px;padding-left:20px;padding-right:20px">
                                            <table cellpadding="0" cellspacing="0" width="100%"
                                                style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                <tr>
                                                    <td align="left" style="padding:0;Margin:0;width:550px">
                                                        <table cellpadding="0" cellspacing="0" width="100%"
                                                            role="presentation"
                                                            style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                            <tr>
                                                                <td align="center" style="padding:0;Margin:0">
                                                                    <p
                                                                        style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Montserrat, 'Google Sans', 'Segoe UI', Roboto, Arial, Ubuntu, sans-serif;line-height:18px;color:#2A3C51;font-size:12px">
                                                                        No longer want to receive these emails?&nbsp;<a
                                                                            href="" target="_blank"
                                                                            style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#2A3C51;font-size:12px">Unsubscribe</a><br>Made
                                                                        by: Sefa, Rama, Nancy, Saffet</p>
                                                                </td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                    <table cellpadding="0" cellspacing="0" class="es-content" align="center"
                        style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%">
                        <tr>
                            <td class="es-info-area" align="center" style="padding:0;Margin:0">
                                <table class="es-content-body" align="center" cellpadding="0" cellspacing="0"
                                    style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:590px">
                                    <tr>
                                        <td align="left" style="padding:20px;Margin:0">
                                            <table cellpadding="0" cellspacing="0" width="100%"
                                                style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                <tr>
                                                    <td align="left" style="padding:0;Margin:0;width:550px">
                                                        <table cellpadding="0" cellspacing="0" width="100%"
                                                            role="presentation"
                                                            style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                                            <tr>
                                                                <td align="center" class="es-infoblock made_with"
                                                                    style="padding:0;Margin:0;line-height:120%;font-size:0;color:#CCCCCC">
                                                                    <a target="_blank"
                                                                        href="https://viewstripo.email/?utm_source=templates&utm_medium=email&utm_campaign=giving_tuesday_2&utm_content=help_the_needy"
                                                                        style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#CCCCCC;font-size:12px"><img
                                                                            src="https://ziitdp.stripocdn.email/content/guids/CABINET_09023af45624943febfa123c229a060b/images/7911561025989373.png"
                                                                            alt width="125"
                                                                            style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic"
                                                                            height="56"></a>
                                                                </td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
</body>

</html>
--===============7441089610961584048==--

--===============3443409471449293251==
Content-Type: application/pdf
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="<_io.BufferedReader name='pomodoroSummary.pdf'>"

JVBERi0xLjQKMSAwIG9iago8PAovVGl0bGUgKP7/KQovQ3JlYXRvciAo/v8AdwBrAGgAdABtAGwA
dABvAHAAZABmACAAMAAuADEAMgAuADYpCi9Qcm9kdWNlciAo/v8AUQB0ACAANAAuADgALgA3KQov
Q3JlYXRpb25EYXRlIChEOjIwMjIxMTA2MDA0OTM1KzAxJzAwJykKPj4KZW5kb2JqCjMgMCBvYmoK
PDwKL1R5cGUgL0V4dEdTdGF0ZQovU0EgdHJ1ZQovU00gMC4wMgovY2EgMS4wCi9DQSAxLjAKL0FJ
UyBmYWxzZQovU01hc2sgL05vbmU+PgplbmRvYmoKNCAwIG9iagpbL1BhdHRlcm4gL0RldmljZVJH
Ql0KZW5kb2JqCjUgMCBvYmoKPDwKL1R5cGUgL1BhZ2UKL1BhcmVudCAyIDAgUgovQ29udGVudHMg
OCAwIFIKL1Jlc291cmNlcyAxMCAwIFIKL0Fubm90cyAxMSAwIFIKL01lZGlhQm94IFswIDAgNTk1
IDg0Ml0KPj4KZW5kb2JqCjEwIDAgb2JqCjw8Ci9Db2xvclNwYWNlIDw8Ci9QQ1NwIDQgMCBSCi9D
U3AgL0RldmljZVJHQgovQ1NwZyAvRGV2aWNlR3JheQo+PgovRXh0R1N0YXRlIDw8Ci9HU2EgMyAw
IFIKPj4KL1BhdHRlcm4gPDwKPj4KL0ZvbnQgPDwKL0Y2IDYgMCBSCi9GNyA3IDAgUgo+PgovWE9i
amVjdCA8PAo+Pgo+PgplbmRvYmoKMTEgMCBvYmoKWyBdCmVuZG9iago4IDAgb2JqCjw8Ci9MZW5n
dGggOSAwIFIKL0ZpbHRlciAvRmxhdGVEZWNvZGUKPj4Kc3RyZWFtCnic7V3LbuQ2Ft3XV2gdoNzi
mwSCAH50B8hiAKMNzCKYReDOA0EcTCaL+f0hKZUk3iOVPK5Ll8rtNNJlUuLRJe/hfYmu/vD955+a
X/9uPtx+/nfz2H/eft61V8603X9N+rOfdkh/1f/ceKH6n5vHp91fzV+7+919/PvwmcY+7ZxwV+ke
YWLzj2lTtNpe2SCCj/0tbaabf9v985vmzwh4ELET6O/HP3cfOuHjtfbKt62USirRXSftKJuPH76V
jWj+8/PulyjeyXjCCsUMGVcgwWouwDZwQwbZWN24iMc164gojOGGtAktfnItpGFGTLO2bWOsYF1I
GzXOj5kopE3LhGlNBVChonqiikwyKpyY0gl+0MwlIVrPtaTa84NKIRoZbKMV385MmEJaxw6aBI3b
03HtT6s1O6YSbaOip1SKb4MmzOg1FTtoElQ0TnM5Dqv5MZXTETMqyiq+uUdMkUITbtAkaJy8YGOo
suyY2oRGyWhLHN/uTJg6GlFuzCxndCFsBFWSHTPPPfvQwDp3mzY7M2aWM86dzc1Lx46Z5x7tMTeX
fHLwzJhZTmZ+cmPmuRvLzqUQDDtmlpOZn9yYnfOQceLZ03GCqrYCaJK0YXMeTnFD9tGNj4aZ0Rkn
0OTd2UGTpHHywjJueXZQlXxxm3JEVjplUFkDVLBytOWG7KR0tpHG805dRqvHDpokjR+ezS2lkIkb
VCe7nKnE6kQiqFSBH7QjPadr0jOg988bvPzsrufz7T/iT/+N/P8h/v978+O/YueXowXWm4fdh09x
nqF5+KXpHrTvPh5SQaPZK9c8fGm+TTXd75qH33Mls++QucONHYreoXOHHTtM7hDt2GO7Hjn2OIri
c4ceOwLt6CT5+HBUP+MaCVwjIaNK1FD8fuo69JX3rRMi7gPh+58jx2LLHWrjsfW4E8JeCRGk991V
Uw41U+h0d+yQ/YBU1xkHiwJa5JvHByfD0RZDS6kfd7/tbr45kQxukQwytkLJBkN1oCgbhKB0cEAH
Q+ngKRvcKhvUEQzouKYdNxT0lj4WMBQL5xTlnJrlnCo4pwjnVMc5VXJOUc6pWc6pgnOKcE51JFMl
59Rrck4tcw4I9SLO3b0ABdgOLDyNUpUMetrCceqMFv163X6jiQdYWXvmwTf7oBZnAUZlyS0xiLhM
dt3s/SDjR7pGn0iHaNfMmqAKFpLMU1BNCP0q04xJ7+GBhuhCWEpCuvlQaEo54enS0NXEIeH0DnwK
aOSGmhYUhNoJcUeVhiAfwWKBDRMdf8LQIVvaIVYtFLVyUtLHSEVQwYOjIPS5QFO0nRRUalgBqgxp
6J6GHYRLgvOjawLqwegCVs1RSWZ6PDw5rMoCdgyXBbcGbC+qH5AfGUn3rLymGMBquu/lDc0NUD23
dO3BkYCRBB8H06WCgOeeIcHdKpVQeODjJ4Cl80MSoHW8ru46bWyMaSD4zmf4+9fxnUIOQr5t56nd
EnffkvOEuBwMEzpC2LvobGAyVM+qpfxVYERoJqLARKjeAZvlJyuqmxlrTTmnDHkyzFhZsKOU2spR
2/sM7wkmT/lVo0+zJLSSELigl55ZWzTIoFWgBg6CzYJUCGvOAnSorkE2GlQoUNkt1Qe4BoyA1rNW
REFuqDu6cGAHqbNHRwYqmwln6CKg64Y4kd6BARDsQxxDw9GZfRlqe9Cc2AWyY6fTeG7eXTlBdnIb
GfJyPToKKcYU+cz1i4p+Pp17w5m+pNpaUx06tmTL+oIA7nj5+4Ha6oGZvxfDa279EFfchFKkozVF
cJCwWBBxrqeT7bymT3kNkN5bSmkOFfinvsMeSvBSueFH6WPTHm5Nzcd4uznU8rvruhytp+jp9tSh
hyHT0apEV/n2ydPT9VCODiV6xZcB0qRNp8T7psNNdwr1NKWenqWeLqmnKfV0Tz1dUk9T6ulZ6umS
eppST/fU0yX19GtSzxyoh/XJVS5ijRMKYpB80ND8Ql5dncJFS7loZ7loSy5aykXbc9GWXLSUi3aW
i7bkoqVctD0XbclF+5pcdK/LRczWLoOLtQJfG5Mlv1xtpGHtei1xPXw5GnrUmaeM6t1bd+Z5LpVZ
xZEaNIKY6km+0If9v7fGlEqa0BWWCF4o8a1Z3ekmbhzm2ZeEj71owroyDaSQ4nAH5Jifqk/U+Wav
h1QcZYR8lKq8L3VD7esUb6m1a9R4bOep7xjO7egYGR2O8Mg2NgdypuZjvF0NB4DydVmOllP0dHvq
GM4MTUdHGzFFj810+/j0fN2Vo12JzuAtl7SnbTrDOLwweUZJAu6AjueS8lhRFTYsmIV1ntFjkOtP
eU4Vr3ptywQxVcn6myH1kQQFWLSuXsLVVqezsGJjPEJbs04bcNrARXgTvyHeDCpYIsER3ixRrSpv
Bju3V2E5KjgTfdYLXuDFt0yOYYFfQI5zGBXnB3JoGc5LDjQl4E4ggFsNu19J8Xo4l47JAux5uOP1
j3F0Qg8Hm4F6yEUw2nRa/VvZmmwNYWSrVYvUA6ZBYWChUrBO8OoqGaal4BAc1C7gVBycaBMsYb72
ogzztZczYb72ehqIp2YR5nfXZTlaTtG7MF/7dibM1y4U6LFZhPnddVeOdiV67TDfiPfw7Iwe2Iep
CsCEweFG8MB64chkTZvm4643R6o1Z0oPN+lps4LVUPEBxwoy1vejWSSzGPUt+dHqIo11sRfHI1WT
kuHtxt6EM8edbzkpyVwIi2HeNk1iGJMSK99cmJdUMk4Lj6zC2zP4TRNRWwO54uzGAhlHxfmWJRS1
loSi1s6FotYWoWhqFqFod12Wo+UUvQtFrZ0LRa0pQtHULELR7rorR7sSvXYoasPWQtGvvuI8quSC
Ks5ObC00/apSmsSbUQWXV3F26j24q0uO5RreNo3KpOLs3HJw915xXlP8UCm8oIqzG04xXF7F2bfL
7/AvNBVJKhmnxV1xrpibhOFdFUtucseSm/jpOeauw87kJl77afbg8znmSXbRXZflaDlF73ITP55E
LkarEl2VuUl33ZWjXYleOzfx7j2mPGPYkAoQowoupCaUyuRBbC2Y3GZ4kBU8FP02UyYf1beZMnkY
oufNl8nDkRfe75kUBxfsYmy6TZM4KZMH/+Zi06ySYVrbLJOrdtCAaNX/feK+5i9OqLEGI4QdCo+G
aha232oktPSFRpNIqDr389l/0VpXKn8i0zO+8m/9GwZgY1T/goHJqfSot7E+AsKvKwHuWPhl46q5
mimmsZlfXUjfT+/71D4na6kjtF2SlNKt4Rtv2yBje3hxk9spoRre7HR3pG9+ngDk5vCAeH/X4btB
TTE82rjiAbGdE7xRhHyHLgF0+YCqKVvm4uZi768rZ7OFDl4QoeAXFNUPX1OpJnqfrQWuG83asor1
YCs3kbbZQoHbyNuyTP706nfVxE2NblweKRy/Z24cbBhX+EIMYzATeqjlkxqXmrvZYl4nJm+Hf/X3
qLD3zf3uf3BgxA0KZW5kc3RyZWFtCmVuZG9iago5IDAgb2JqCjI1OTMKZW5kb2JqCjEzIDAgb2Jq
Cjw8Ci9UeXBlIC9DYXRhbG9nCi9QYWdlcyAyIDAgUgo+PgplbmRvYmoKMTIgMCBvYmoKPDwKL1R5
cGUgL1BhZ2UKL1BhcmVudCAyIDAgUgovQ29udGVudHMgMTQgMCBSCi9SZXNvdXJjZXMgMTYgMCBS
Ci9Bbm5vdHMgMTcgMCBSCi9NZWRpYUJveCBbMCAwIDU5NSA4NDJdCj4+CmVuZG9iagoxNiAwIG9i
ago8PAovQ29sb3JTcGFjZSA8PAovUENTcCA0IDAgUgovQ1NwIC9EZXZpY2VSR0IKL0NTcGcgL0Rl
dmljZUdyYXkKPj4KL0V4dEdTdGF0ZSA8PAovR1NhIDMgMCBSCj4+Ci9QYXR0ZXJuIDw8Cj4+Ci9G
b250IDw8Ci9GNiA2IDAgUgovRjcgNyAwIFIKPj4KL1hPYmplY3QgPDwKPj4KPj4KZW5kb2JqCjE3
IDAgb2JqClsgXQplbmRvYmoKMTQgMCBvYmoKPDwKL0xlbmd0aCAxNSAwIFIKL0ZpbHRlciAvRmxh
dGVEZWNvZGUKPj4Kc3RyZWFtCnic5VpNTxsxEL3vr/AZicTjb0tVpRKgUg+VokTqoeqhCqUIFdSU
Q/9+x/aG7HqyIaE7ObQg2PXgfZ558zyejZi+X3wV35/EdLb4KVbtdbZo5MRbWb5E+j7vGlSYtPci
gG7vxeqhWYt1M2/m+HvdlOcWs49491so8QF/7sXnL2i8aSelCQ+NBz9JAGBx+KM7BGncxEWIAe2y
HqbJd82nM/GYVpsEKZXSSkNetz8+7zyKbr7g2rrZsFEmPq0em2nh6diVApqCVALEr2/NLWKPiAwO
NBs4sp0WMONDy8gHHpEMJ4V1wEBKAY+s6IkYY+Xo6M6ywoM2AjRyo7Vj4CbDOywxjPDJexAK0zA2
vHGRE15BSqqyQlnLQE6Gt9Fxwifv8eI5uLec8Mq5BI+p9SzkZPggWeGT98IyUG8kI7rWHtENVjUp
Gahp4TUvfDq6GYhPRZILvHiehMNIjPO88I6RdybwthRgGYgcR2CGt6kH4YPP3mNiA0OVB054bbHZ
NnjPJMoCH3nhA4/mrecDz55bYCvCGT6wpjV7L7zjIb5Gnx+LMuxOsQy8Iu97Qb5YNtNr3O1RLG9F
ceG8XJb4kuNwYJwSyxvxBt/xzVuxvG9c+mMx+GwIW4PLBlD1lKslRsvjJOiAI63CZkWonVLZ4LcG
Xc8ggb0biGNvqHqsUP1AqKn73hGqrQMhoQLUUzgTYtJIWzVmQsiMIaV1poRsMFtDPFGC6tBfk6DO
FFumdFAuX4FSSNc1Gx3DRc3XrMZwNcWjSX54d8fEaAx9n+i2C3vYIUK42h1Hx3BdGUDWmVTb0A+p
y0BJUTp90uBN+URWPGwMdhKC9HhEa1/uIFk9jt3mw9s8XuEDdgIQVToVywzTBzDdBdL8bNDlIdF/
XFULqPxA14U0I/YBYn+Bu+bijGtv2by3gvwP99ZfCSzWAos7BRYrgUUisLgRWOwLLNYCizsFFiuB
RSKwuBFY7AssnlBgRg4LjKT5nxEYVyeQGkgLbrDu1uc81L0CqDquF8v93lLNE6hSKnfKR3QnxEuw
7F76592Hzpow5Forri3nUJ+GJAlAxDXwrsAaXo7Lq8O9Jp3pUFO/rxEgGr5ijxTLCe4rYw5vXwgX
dY5pk1R36acQaHqVs/I5LlIviFSJk3V6lKzFTBL4IntDLyzsYrZ2UzoVKYxEu+RcISWHbFKCQVRB
CCf7muiG0MlefrUziSytDtbNAbWBPcWt13b4dHyF17MTeb1tw8fw+nLr9WH/jyLmzR+WFXfaCmVu
ZHN0cmVhbQplbmRvYmoKMTUgMCBvYmoKOTQ3CmVuZG9iagoxOCAwIG9iago8PCAvVHlwZSAvRm9u
dERlc2NyaXB0b3IKL0ZvbnROYW1lIC9RU0FBQUErVGltZXNOZXdSb21hblJlZ3VsYXIKL0ZsYWdz
IDQgCi9Gb250QkJveCBbLTUxMy4xODM1OTMgLTI3Ni44NTU0NjggMTg0Ny4xNjc5NiA5MzguNDc2
NTYyIF0KL0l0YWxpY0FuZ2xlIDAgCi9Bc2NlbnQgNjI1Ljk3NjU2MiAKL0Rlc2NlbnQgLTE5NC44
MjQyMTggCi9DYXBIZWlnaHQgMCAKL1N0ZW1WIDQzLjk0NTMxMjUgCi9Gb250RmlsZTIgMTkgMCBS
Cj4+CmVuZG9iagoxOSAwIG9iago8PAovTGVuZ3RoMSAyMjYyMCAKL0xlbmd0aCAyMiAwIFIKL0Zp
bHRlciAvRmxhdGVEZWNvZGUKPj4Kc3RyZWFtCnic7XsJVFvXmfC7TwubFiShBZDEe5KQWIRYBIjN
NgIEYgcJg22MbYEEyAYJhPASO6kbO02z203cJmnTbG6WJlMnzbRZOm3Tpj2TTjttMm2nmU7nT5tk
JtOm00yTZjpJzGO+e9+TEMRJ5+85/39mzjGK9O763W9f7nMoRFFUNnWSElHUcLC6Th/fdRhGboTv
gbmFY7OPXPz+CLR/S1H2X8xHQuFIj/+zFOV4HsYa52FANqV+gqLKoEvZ5heTR99/SDYOfRtFIfFC
fCbkvy5QQ1HleMHpxdDRJcpHrUD/UegzsdBiRFux8kXo/4CiXGcokagBnaEkVLbkTokbIJTyT9E9
1CytRhKalookYgktEv+Scq0/Sx2dBCg5+OixwU6GaqeY9YuSG7lu5M5i0dfaKbS+vg67b5MM4NMo
LUVjYsV3iU8DtVkUxapYVSn8IEp018WTopmLMPP+CZO4D46mZBRFJ0VBygUdbaO7Tq/TS7OkVqnD
brVkSbNUBTCg82jZhjpPI3xU9Q47fKRZDg+qmovVsiUI6QpLGEeZWqUur1TJzMZmbtd2RpcjRlJp
vtJQbMt5XxR85hlzicNmMCCmRG0f45I+qyFfhVi2QMEoe9GOW0xFChlCcjZC0VQjYPITiZhSUpXQ
AoS0BYCQxWFvqPc0arYg1KDC6NitBCFZaTH8ldrhp3AlL0+vbeXibVqtTIaysuQKfZFV/q5ELCwo
tsNibnhtfqiwSKYAVGR5xcWDaPu1DiOsx5ggwICSfBp4EwE8MPE8e1JPnZ7HxQ24uAVk6gW2ZWXM
6TampGmOui9FgBvV7Mkvr3ZVDzZ7NFPt7V0d7toSDZLlGAxN3Jyq0azJFRtsgzU1tZ00nZNbVNjO
7esqKswTm8u666r7yzDJXdxss16XJtmieM9B37dHyRZoqqomFqwWi2WgYYm7a8iolStYVitnlX40
E65oMRi8uXbu8M4CHR5HqnxW2QcTVS2osLyW6x41FOXJgEmy4qJB1PZJhzmPZxLIy7v+pqgWuNRK
+SmqVMrLylNP1KVBYIhWn5KhHUYJ97QCIzAXtFIHKJxDhfkj1cO4p45WnGRqGyc8Tai4dO/kTx2O
/mbWQmt1FotWi0aGzyz2NBTlS8S5uQplntozO1lVVISuc/SYGeSwu31HZ5T61pYDbVXbGhuHmOPV
rpISR32FTq/XVwx0tKNSU4vjKPf64aLinByprLHuOoQY8zWo1aMrq3TWdVQ4EdA1wSWkV4AeTlLL
IH8Rxkwq4NvYwAsNi1qq5enAYnZDl7XgKUJno0dHKCVkCdRLN3RZ0CNPljQFhgDBH2Cb+D8PtoJi
ogKNuWPvVEcH6u3/5HX3v/jEE/PzeycfeODZf3v22Wh94Kc/49782VNPR2bRcvz733v1mds/PTSM
evuWEyd8FitSfWJkdJu3tm587Ja5YFt5mdL0WJdvtreBYcrqW1p27DDXItYiCnG3f7+hkTVpCjq8
5269985Tp7q747EXXnj5hYe/ODGBTn7snXdvv2M2/LVnfvm7H/3t6gpCA0O3nXvgC/fd39vHMK11
wftqappb9p+6/77Z/hJm24wKdUe/fGq4xWJD5Y6xQPDMnlabBfi5ff1fRHtBTzRUKfAzzRdHmhv6
NDsxkzGL0Q+/lgih+sapfYm/Wpxqat47OVBTU2M2+/2rE83NaF+7KIhuvuKueCLR3IrOnbhreXmp
sbHVaO72x79y9Sm//7FfXDUBdkzDyXeKWqlqOFclFbROn2VtEDwdIMD7tawGVpWSMbHLBpESZUuV
ygKjVf7H8kOe5u0+d72mQC43FLUjCyova7bX1XahwqKAqJXLvaUEDETJRi4kTWaY27EjiZZbDFpw
bezaz5I2m6GwC/20u7CQZrHnVa+/RUvF/RTuqNxaq4rovaBFVqJFHpW1gVcIVPmtb+n1NrPRmG9l
Wlq2VZSVqwvQqdoGd0WBXdzP/fuOtddHjCak1th2O6v0OmflbrrKrKmp9lr2wllNcMY/gS4X47O2
etB6QZfBg07k5Rn0Xi7ajL2mNEuh0Bpsyv+QiN9/cqiwUJ52k/SbNzAl8jwF8ZL5EHseAtjbMeyU
9joaWCLeLI0u5e7wWfUOEX+8fktE4Y+v/ruOvCykzGfRfH9NXetPfrKrpJLVNXMxVi6zreXJCrTd
3OQORp0rR4CcUq+xK9+RiC9+79k2VV6eSiGnTSZaq214jns7Zq6U5YAfy8lRa6tQF/fmaGFRbh7g
r8zVmnrpt29iGCIqwP/U+uuon7qAvT2x1wwLfb3CZETIaC6vMMHfhXSrAsZhZ/v6v9DvgkZD1EdY
k6WCJqdiFlEt3k2kXQf9riU0ffim+Wgyef+x4WGd3tFYpBJLSljPpKcPoT7/iV09tTWo5fzEboSO
rH7/W8ePoXavzwpez6ppqDcVd+4+c25pua08BmynGrmE6ARg4KPGqXnAws5jAH7FTfiu512Pldga
WFraXQmfTK/c6LHzfluDV6Xwxfhv8n1EXEg/UFY+NfmpwxMX7NlSkRghsUiabV9wo127b9veXiZX
KBXOwtmnm4LuWnTgple/dLQL5SlrpOPVmgJUVPheZ1UV2l7j76qqRGhbtf+BSq0eoYbJR+4bGkCu
6ht+gFy2zo7RY3t2tSAkkmRr9TmQDnWEk4EgUluKilQquVIqpqVZ8lp379yu00NVtVod25a1x6jT
mczOCtoPTmPxlqE2d33s5kDbxZeq7eWMs6Spucnr0mrEUuDc9PqKqF1SDTlGA2RUlIbwSyXwz9Pg
1pK+FQtQpePlmaW1Er+PVAKD9JrGFN8c02W5XZ3X/qCzJhi4s6XXXXSrVb6t/cQrHe379j/YMu7v
24XaJyud4BFnWjptdWZQK4vtJuQ64e2U0cqrDnTNxIMBdTAokWV5uLfOdHgVXMPd/QPxq/btVyST
onylnf4BOp/nqu7uaG7xrjlk2pL6utYWT/00eLd3uVXRFGhBFaZE5HFrGzeUkARWrTSdqOgybB7U
QSJ4Ax3vcLGq0uuWdm97z4mx2eORO7pqbFUoL7e4sIsb0tfa8nNzs7KVqiI9g3TZsrra/j1NvSjQ
MuysYOhfz3170VmJQke/+fc3JCFuycsvjuv0OJugtTl63aRIPqrV5eUiJFvhvh8uaXCUI9Sz98Fv
zHbrwIXQ6++Dl54EP1JE8j4SGwWtBRFsOAm3SqXL0E1AGJmOXv+x/fvQ2avu9Pf1D2aBv9YWlcrf
La+qq6kf7elGqLtnd62rlH7kocWFr//TJ5KoqKhBtOtGlndhazFO7dLp9+x59PPjOw1qiFRt66+L
7gFM7JRnI6PBNgI4NWRikhlL+DzOIZgKJDAf39bc2vHJcAQi8+MLfoKVwS77j3I+oBjKc9+pkBYZ
nVUVI9uDCFKa6cDUDmPx8vKXHzt3a/dnU9hd7DwrRJWvooe2ueuKCoGc/U88eWAagQfqAXmXSmiq
Xohsno1kFMcOt2DYAiv5oAIfEmj1WrcWXYWKLE39nKrUZjbJctG994KGBkfn9o3WI52hWKfTs9Zi
EwtOD1KRn9Lvrf0yaSoHL6pWm827acbbeHxiZ0M92lZRW2wwKBV1Nep8iOyu6mfbvIAd+EXRiPhX
ON6XZrENlKBj2CdZM1QUPiyf+IhGxtdcaPupq1G3f2aPv9fC6vZN3fjpmXBl17lXPKg9VOZgSgxv
vMEiy9NP3ZHs70f1DbMPTO5CB/ZfPTV16/3vuFF2ll5bDmf3o0m6BL2K6z0Nq2X70U84J3r1kzCz
e/11+mawlhbMM6ugQ8QrbpQagKNV5c4wDBKNeQ3ggzQ9YobYHNjhcJiKx08/uXM8OhAyawpkZnNh
T8/ubWUOVOm8+nQZ1vHueE23S6nMzpKJgty/XFNTw1odbpu9vH3P2WWfrzgH6ZDjY+1ehOzWhm2V
FV5vQ93IbJdPq4AKSifUaKKzoI8dGOOM8kOaCuTuLaUEVBnSTVXGpihbFW5tae12uw35CClytFAl
RTUtel2OCMkVJSWVVa7aDpSXg6uL2UZGDRYLuqvQF5TL/ygRr92/yJQ4HMHmO7lfDBv1eTglUKss
ih5k+2RFhU4LxWA31y9UEaqcwsIh+t9SqgyU7Fr/jcgqfp5EzCw2S5dWABIsievVpaoC3tIcGpG1
mzsz+rubjjrKW9p6owvxujptAaNXqys6e6Ijo/6eq2YefkP8/B3nbTcffyA0GmxutdQhe6nLUKBB
UAWZq0eGk/EDBxrKstA/4nplaP0N0ThoZQmFa28+CYVPozsjIGr48qXRjUg5khH6YKlo+9H+gd5+
kOPVp6+cmkRTy09dNfEXqKPj+LFEfJpDKqhy212dQ9u3oW07lqyOMvGvWLnF1tu3e8+JPSgcufuO
j90RvBfR95+7dSVRVrb2ySv6JiKRtoq+3uvvWF6CMlgJWHYCpyYBSw1VDhpcn6omNAWpnNlTkCpG
0rKFmc4dO6KjEzcu3wBH7zuw67Hk9OPb62drGuqLKypZt71+e7XXoKenXvzMZ/ogtN78BPfi3992
rrML/egvXr54zyeclXOfRUUv3jjnNHv677kXZxhxwMNNuFVLeTcyDE9KdLqNXAc7m1IhHlqFQk6v
zxKCJbYkzEE086nyir1777h1757a2jvvdvtmpu+5EBpCTY2oYBGnW/WNe6cgnTcYnLfNDNhsyLtj
Zrq1BVm8dPRwr3/o8MROhIZHZ309PaHj3XtnPz65F8UmQBGGvx1qau7Z19gIEHqqXTUVV5za0d83
serrQQB8pL1+P5Y+ZNvi34MGGrBXcvOWQ2pzawMrTlVrrIMYeQMvcNY1wGpQodXnQm8h9S0375pA
d17g7vrrxNALN1x//fUvBebYOvO8SLdiKmOB7Wc/9Y31R7+5uwjdeuvFi7eeRagQ23AevqEhVbIQ
2z7MgEGOG8ZL7ECQL39D4Dx7uqOuxqTBpqvXtnGzqha9PkcMqWnXQhTlyfS6Li6i3qHXEaPl6//z
FyyWQU+cu3u4WC8TLFbuR4GlevcqNzBWUCSD0p4pmUTu28BU+cKeXl/mllGU3MPUX/IeRlDDdEG/
1QnhCxkHvmlxkPuW5OSes0Ec8/U6M8QKp9OsKyjAzkW4mnkPX83wS+0OfDVz8Vs/nZ1HZhNTotch
mbTMoVKW20/RAxuXD4hiKEqiAmlCHESswCcQpJY3BuESZiMoqtgtIw0f2KNFJ+hmWY7JUVlJ51VW
lZqhapBlmxzOyrV3KvstOrT219C1O53QHbDoZDnGMrzS6bQbc/PoM2j/PrMuX8eyWqXRvOfib6bM
+nw9cNxpiqMkd2NGV6TLXAmaWQIa8hzQYv1gNG9IaWhdKmsnWVHq2iHFcXQcormveu0d1xCrNthA
X589v3+/tx3NzPxllbu+pdpuK57q6kSoxNLS1l/dQ2/jPpc04njuLj7I66+FHR1d/MzUfqhn2nPE
EqhHksNdPtaC8oHbdrCdHYBhM8aPJaUqnyHbraygy0Lu4RZt1mlAXcOvdKCrkTxqrZayUNOpSu0D
3NuQEBWo3C/M1bicTa22gxdHKysdJtAMHTtQKXpMbi3Q6atKJ8XXcCam7CC3c3dhiUbNLY6q1SAa
hbKiaZn7W1arMBsnRUWrxTaWeztks2nkCFt7F2RyCKyukLKBF02VMKkSL627pWw6L/ouPbnn+Ghb
W7mxYM/e684dPIRQbOELN+zZhda+g05KFIZKV01/WystenouWlUZU18ZiSRXvvPjI4fR5N476ofZ
WkjtW7CRU3LQTRa41QsdlFnyknxChFK1GF8a4xpfZE8XzjCj0aQvmlLVtDSLfgtlLTbUB9bedhdp
ZHKUlV3xwjpVnpVTaPBxgy6Lx+32IuNvZ7p8u2lPX2Fx5ddfKs3JQblKja4dfdnN1pZV9NIPcEfv
r6wUs2xeljpfrdEpvaiJe7pBBVmduoBmWbHS4CgLoAU0fcZZJYK+Rmew7uBeRwU1YPdqpTo7G3RG
JNdZbPsoQS86gFJ8r6MXbVFZrZ2YlXDbxyuF2GaOXhx0DVg02KvS5dMOh1KhyNPrjuy+qbm52oWC
Uu4J1m2M8krJIk2B0bR4cb3fWJCdoy1oaCAedf11SSl/q6PZ4FkGuyDqAA8b0rcRyCoSWXEAc+Sh
yRqlUvnlx6u1toJGdENHsRpl/9WX1GpVPZKM2Ljflv7w9xbuj8WGokZRKyuWKwpNDs6GTh/zaGXA
D5FWWaLWcHb0vVpTvlIOHJPtX2uiFWtv0U926PUyjB1Ys6QHeNK3WfoEG/SnvRCkeTZ+NRlNJSl0
GfpufGhoeO3per0+O6eG2yPLNpdWla/9McMZ5ZQ77abcPNUhlNds0GiqjOjbDpZ11XQVnKcf5NqX
HeUSCAH5eq06vwbdxx3e5JSmSrSqlFPirs+f/o+AzViQnw9FXE5esWlHwRfAqnrBqoYgJyjGvNcL
2rtx/ZHO6qyoMV0ukWwAExtanY3s32e/JfHxqb174098ZuF0ePbLn3oEreWbzY1NvpG27Wikdbyi
uamQRY31p09/fi9CkekH77nqMwiduPOVHzz++MoBejXZsysy29jo7735mweHCjTA5PV/Xf+txMjn
liIWEZYShhJ2WgnP3RuRgLcrA+qjf1do8VeghyuHSwqYi/9gsPgruYmKYUaDGouLG4vrxc9fjNLP
LZlKgUPIZZp7/z9FP19TLBvtLFttnBcFt2s16ixci3Wuvyo+K34NqnAKEWdnTd/rZvgdh1jwOyTf
JMPi3UZj09z82StCM01NDQ2HDl53dM+emHHv8Sse5l586EqEgoEztzxy+uOlqkK1Lk/8Gnfga8EA
2rb92uu+94Xjx9u9bvft6vP9gwi9+uBrX/3s7eNjqL1AZXBiLQTGSEzAExxRUrqVRWJLBisQ78IF
Xuk3rAa81DJ61KCvctnsjdw/QHDpK1t7t3IIeMM93qbVdqotdG5xBeRoqGn93xvlCoOhVvw8q9U6
HBNcDfeDFJMQS9N79Domh1hyGbOTW0VXjFUUFhRAycnfTopbAEs2xTms9VvkJeBu1Yir5Ja8fJOr
uv9RkFXF2nsEn1vHbdUsm2VRiJ/nftXP1hcWXtydltGDclVtbQDhAIvtUrwIZ1mAJz7hHppXVv5y
JB2v6lL3Z6Xp3MbDv8NRqTJuwnBBkCWa+NiOXS0t4ciP1r4BXk2LCiH40qrb9lzr70bI07T2NFtZ
0XC6o8NmQbsmHtrbE507D2lsWfnE7pNNZWUGeqm4LXhkb3DMbmdRXQnkkglzGatjA8FDU36/PJsW
mYytLd2HBgeQhitfe9LQ17vQ09FhL0UI0WLgoA8ssg+oyiO+EFkRi9nleIY+w81HUIy7MFs5WFUk
ft7yvlc8ZKiYyAUrbgd9/XfQVyXmCc7vVDSfV2hoTyMmXJPPE67Kd9jp87+7cAFdeOw97pG/QOj5
R18+P3MlOjl936PLSydmxK995avcW9yvn3oa/eWXUQkU5/d0oGO3c7/gfnzP8WuvAXSaP3scTjSB
AKbAb+Ti2Ii0VpVVxTYgyCFUSDR1/tzau3TzzDkugJ47yX0dda6IKi++Qh9YuwfoU62/JmGI1ISK
DfGOPCNcopSzcTRImA62ppSbYLkGm1zPsk3oD+OGogrUhJiKouJtkjxQUrmxavL934mZUXWxSgn+
MFurZaoOrNXR350vLzIYchHNYh5x56BaeI0y4vejEuLGhcsAciFA81aML0wRMFyVz5c5GoKHyDW5
cOi6K2+65aqTk6f6Y9u2I/TE49ybj10AP3YVd+8XwlednDn/8Pwx1Fk/Nq64u38g1yR2uUZH9ta3
Tpw8+SWkfvIrCPj6xisPf1G8tHob9yL3s3vAGVx5Fpn/8dMrHg/Ob9q4VdHnIL+x4ZuqjJv91BWQ
UFjjW11S3jZ6ROlqIv2mRaTLyzXoOrn9KncRLveD27Z7j+3bj6488ZjbWWmtrzmsVlVVNc/6/X29
8w0V5aLg+/8wouMrCUVuUWE/Cs9YbCi2+OSPT5+G6tVUyK6toms6HZDGo53jX3po54Se3GPkrr8q
sYAUMa5CqNOr0gVt6i1MKgpq+ZQy/VaMJBSiFXTB5bcXoNLSg4ee+t7cfKWphMG2Vj1YokcKucXi
bd9/5MA+qwUXbOIHWXabcZbLfzo86+9Dvu7VkX9C/2cZrJBla9i5tTd69u51uy0sgoxq9Dn0JiQb
GM/C9dekOBPfvnE/APqWqXLClRGkG2ltyBxNhb0G6XPVZnOx2sF90cb9mnuD4W4rz1OXMPXoO9pa
Q1HZW9+3mQr0MhXYXin6BeM26Mvf+I1DrtBYG0FFUb7axR6+WCpSXvy96N1lrUWVD3jrtCXM8too
7Z8LOK0qWX62GA/qbNWJtVn6/rhTq1ZnyVnyful10Y2QH1mJTxAKcozbppQyTZUanSq0qguQ5lvP
apE0T5nvQooaFVPI/cLO/bxArTYqqyAXApyMTCXnQT+vK5blyCX4cLGyuH2tlX6mVqtVZmXDyWAr
dDPwD/xK6aVSnIzSjG7eUkf1W/SIFFhsKiEx63BCgirNsVQ5larjX4Ezqqg2ioJprOdSx0dUTYRa
8jYK1bk3LrylWeJXuKe5kMsokysUEOK6aqB+EjJT9PXnpiY72lFv353c+I7t4YufzZfLsx/dvQt1
96zW76LbaAQf7q4tRZTRNDAYTQTGWO7eKxzlufQYjdBg/+GE3w9lFPAH8mSRHiSj5+9FEcvrmNUD
rjt1E5qTu2anS7nf7yo25heKbBL6q2t/j1z7LBatPI/jWPofUa6spKrzn9k1SG2UZcZ9ANcAcK8B
uNuIxNO3mkLg2vRGTqhF6h2OzVWIh0jJgK6xK5RMjralqx0pVSwyONmqgeUf9gOR3BVlhnzUcuz0
9oKCcu5t1mAZffRzXVY7zpTlMq2+SmHet2+3Qa2Q40SZmf0M97OYVk8zjFqm1Y49/lhQqVepEcOI
NYUL//pqqJDcjuRyy6KzgHkzr6sfsKNUBpx6zUYyKOF61uMRNDgXXa0p12jNf/OUUpqtVDqQ3KJW
a3N03GO1w8O9jRYw4SKD0+wuzSliS9gW7mcKk16hdQHeanVh6TZuH/obW2l+dq4UalNxrsykaLr4
/DHsthlzWalBh5BGgZCpePQMHTNWlMjkJM/3QmQyQoRoy8z6+JzPs5FobiSi2CMz6ff/utTLF484
xjA1A4uPvHFstqsztpjsbN/RCr7UWNKLfq7vLlLPRyLHuc89ef3Q5L3XPtnhaYzUqfPlMhFkg1fd
0hdFT33upQtnznZ2IZXKgqb3moz5SpyuWqe565qKil794i/vPXdh/zDKzSstQKAv1eSt+Ou0RCLG
N+TYt9ESzudHX5OI33tVYiJauv4q/V0+n9ZsWG36+rE+dQ/tyTDvZwQLNpv7++fGa+qQ3uww6fW2
Atag04KNOyqxS8a2vPbFG3aO7/CiivKmSoNRUxCow5tEXcTc4fSXwMifITUGpSl1b7w0bsx8f2XJ
eglVmHOyjMVBrn68yJCXm5OVr9ZZW8QjZ9//43xhEXlljRQyvS5O33aNw6iQIyP2Hnevv46iEDf5
3GfLW19NXcabUegjSbk54zVwGe6ZzWWkIwpuvBSG8bWp1ERFmdmMuQg/oqeAi3XkLb8u487EYf3w
MjCVBaMrXh4otYAl0Sq1mdn2MlR7Dqdz7W3BZTqclaKb5IzBzFRVHRBfw5UgKxvhQn6WhVDBndxc
2BE/yr29s7xMrcaY9a//RiQCDoPmaoSXCpAJC54yfR3Pp8G8LqdCnfCPEhr4dHhf/cjI0VuH2h5a
amlB4dPvnXBWabVmnUHpadSy9kkfvm/SGx2dXd2mHr+fYVtax2+aEr18vKvzQM/oJ26uGg3G7lm5
HYzMVqjVoCyJ0STJQz09092+2mIbsLo4p6KytdU/1dyMbsN4k+9ezZk39yvb3sH/qG/rH765lD4n
wTouTQ/CHgnNLSOtllo/uU5JnyOQMv+8ks+DUcxTMpqmGiWfp5SiBqpD+iC1S3QXtR2+NIyr4dsE
7Xz0Q+oUzLdD2wPfadFd6+/C931obwMYPfAsg2c//QK1B9oy+GI4w/DthO+SxEOx8Myj6fUEtBmx
mCoRRyk7wPRBX47b8MyDbwms65V41v9V/CLVBX0NzDVBG4/jtV54muCpEtrb4JkrfZEqhLYacHDB
WhbglkLfAN9cvA7ooAE3O/RfgvbdcL4Z2v3ABy21j7ofNaL76D76WvrvRNmiRtGnRU+I/gDV7R8l
eyR3S/4g7ZR+XHqz9PWsgaybs36VXZp9U/b3ciw5yZyf51bmns79dp4nL5H3LVm17ArZM3KxfEJ+
k/w/FWpFv2JecV7xB2W/8u58On9H/nL+j/LfV+1SfUWtVlvUIfUZ9Xc1ak2MSMZLJbBn4iX3gb8W
+hsUxc/TRWRERFaaSQ+3aUpBNwltEbWL7hba4ow1EspAf15oSykL/VWhnUUdpl8S2tlUDaUQ2jnU
J0RDQluuEIt+ksINyVUvCW1EKdX/LLRpKkv9B6Etopzq94W2OGONhJJpHEJbSqk0bqGdRbVquoR2
NmVQvSy0c6hOzceEtjyL1nwbICOxCM6SFX2HtCXQzi96gbSlZPyXpJ1Fxn9L2tmkfZG0cwBRc7FM
aPM85Ns8D/k2z0O+Lc5Yw/OQb/M85Ns8D/k2z0O+zfOQb8sVBaYK0s7NwD8P41a5nbRlGeMK3K7k
9+Zj3Cr3kLYG2urKedIuyFivJXCuIG1dxngh2Xs9aReTNbeTtiljTUlG20bWP0TaFaTN01hF2mRN
dgb+2RlnyTLGZSlaHqYYiAY1VC3UQQw1Rs1TEXgOUnEqBt8kdYxaIiOd0EtAG/+GYDxKVrhgxkst
wIehAjA2B/uT1ArpReAZgdWH4TdMVsrh44feNIxGqCMwMkygx+Dc1DkDAP0YwF4FOAzAjQPMKDUD
7RloL8FcIn0Ok8a+hnJDy57ueSgnwSEEEJZgLQPnhuAcDGOGOiSs7YPePIzi2VXAcSVNE+ZDlNCx
8KH4zBJeMFQH9KdhBo+GCCc208jDiQuUMuSUVZidIfTi3izAPgJ7E2RkFVaFCecYGE/JoxdwwtyJ
kn0xwttWsj9CVkSoRTgTczpMfhkBo9RahoyvwAjm31Jaght04PkkYBGFnSvAhTFoLZI9DDUk0BKA
tYuEk1i+c4DrAsF7q760/IndzJb9DOR1gwTfBKxJ8aScGid8WEnj6gG8sHw3oPOwNyCPUEGANPYn
z+elEiI8xhodJhzEuBwi0pr9s6zhgys3NLuLrD0Ca2NAOdb9WfhEBT2ogm+Q8D8GPInALv7cBMEU
Q8UaPU7WJwWJDRB8w0TGWDtroWJxgwV8kJNYT1YBjyWiFbx+zBKoSaLvu4lOMoQDx4gO8jqTTNtB
ajVDTmcI/AihPUIwC5N1S4K9OAlvY+ScJUIDv3dGgJLCOERgLxEpL8KqJJnDu6YJHin936rLSWEH
b1mJD4zMpmlwpvsbtvRB7iyRfhj2YO46BbvCvos/15k+ZysFUaJNRwifZoinuRTPjgiURokPWiDe
JuUVt/I+TjTgGLGJKNhApm1fGjqPw5/L20zPkdLNBLGcJJHcTFq/L0VB6vQP4tWaoQOYEp6WJDkv
ZTkJ4m2OEf2JA5dixMOGPpRSXvdCm7SK95Rx4Zenim9jn70keG6M7eG0tfFw8EocHz5KR/kIFxMk
swE9ZSFRgcsJEktwJIgKfHaReJfyIZiGBULdhgfYrNVOIpkQaYcFPfhgBNhqCWUkEmI6W6hq+ESI
H8JnHCJ+PkKkGoIxzKE5WJGaqxZg7t8SVcoF693wFitpjqWw+b+J2//NOMkYt8AYSMFgTGltPghj
vJxSWhMh+cWCEF83tPujYn9KKz88/mPJjaQtZyUjAvHy5rUgIpw1R3Q5JsjdSWhOCHGZ9z3YM4QI
/3k5p/SY16slIcrxJ8QBKh+HY2lNCVEb+c9Wf/b/QBZpDoUI7ZhvUcHXhwVbnQHoi4KNbERAhkS0
BUFnylI4frhsKRz1NmVAIO3yDB6FSZRZ2ORnPkjjR8Aj3jdK9qVWX9q7Obd4txTvt+5eIJlFdAvd
Kbw2stMNq9mIRCkZOom/j5NTZtP9SIaGYL/FS2gFoG1EWB7raYJLRIhUq2lZZvoSXobVgsRXiJUs
pHFI2fVmXfrvczUzwvNUZkaazTq9wYkjhI+Lf6YcU9EAZ88xgTORDAzC5BefucGXg7BiJiN2JD/C
H/OeP0woSEW8lk1ePAQQ48TjXLoe4XO/VJTZ4E8qkm3wKNOnbN61QnwFL6tpge5Lx9zQh0g0kaZ+
Rcgok8R+FwgGeD4zov+5GpCKb37KR2aHqW7oTUC0DJCRXhhjwIsGYGYcel0w2gUjDlgRFOYdRFIT
JA75Yd1OEuN4GAH4HYL+buLjuimG9HGvH9YPASy810ftImf4AFqQrAwQ2IMwOgBPn7AO7+iEkZ3Q
x+0e4gX584ZgF19d9Qoxkcd0DMaZNIWbseolJ6YwG4ReAOD7hVkvwO4l8DD++Pxu0h5K49ktYOol
PMKQMcxOwGiA9PDoTniOwLogOd9LaOaxHSI0dMM8T4uPYIBPdgm08usY8v/i8DNYRhi/AfhsUOUl
PPATbDb41wnPEcAcw++B2TESIYZhZxehNEi45xN4hqkdIL0NqnhJdRJqMFcxD7qgPQjfnjTvAuSX
xyWQAW0z7ybI/MYqnj6v8NtJODdMerw0OklvjMgKzzoFWQYIHVtPnSCa6COrvITiYFpDuon28tin
tJM/YzgDE/48LNtMXFJazXyEjfBQUvM7BUl/kC+Y617CE4xXMH3yh0F2PczU1dR6mLH5CDMYj8WT
x5YiTGc8sRRPhJLReMzFeBcWmEB0bj65wgQiK5HE4UjYxcjl/sh0InKEGV6KxMbwnoHQsfhqklmI
z0VnmJn40rEE3sNg8DVuxo4fHicTCC0szTP+UGwmPnMIRvvi8zHGvxpewSeNzUdXmIVMOLPxBNMR
nV6IzoQWGOFEWBOHQ5mV+GpiJgKP2eSRUCLCrMbCkQSTxHT0jjED0ZlIbCXSyqxEIkxkcToSDkfC
zAI/yoQjKzOJ6BImkJwRjiRD0YUV11h0MbLCDMEpgfhiKBaIzK0uhBIpvrRsmWaEeaZsMDqTiGNM
yscjiRUM1eOqqSHLYTVZPBIcHNu6H0gJMclEKBxZDCUOMfHZDxdDepAwuysROhKNzTHDs7NAEVPF
BJOh2ELkGOxNRIGXTmY8OpMEwgZCiXAklmRqm911aSSZldWlpYUo8GM2Hku6mN3xVWYxdIxZBc4k
sQzwMJOMMzOJSCgZcTLh6MoSyMXJhGJhZikRhdkZWIIBh1aYpUhiMZpMArjpY4T/KS4nYQKElUg1
ZvEJTvwkUkqjs5SIh1dnkk4GaxfsdeI9qQOiMebIfHRmPgOzI3BoNDazsBrGqpjCPh5bOMaURct5
aWcsBwgfhS2vHJibichKMgF8A35vHIC3p2G1Eg6UReGUZGQRCycRhVPD8SOxhXgovJl7IZ5VoJRA
ThyOgt/V5BIodziCycRr5iMLS5s5CgYXOyYsxwIBgMCf+eh0FHB2yeVYQ2bjCwtxogACq53MdGgF
cI3H0gaQEkLZfDK51FJdHYm5jkQPRZci4WjIFU/MVeNeNazcL5hKOYiXqMUKRgyDubRtX8om/05Y
MYBX/Biz+WAcaMKsiRyOLIC9EnZvtn7Myk32L5ePYOGsEAMCuoEFEdg1lwgBZ8JOZjYBtgzaMzMf
SswBzZjHwCuQKGxn4tNgwzHMlBDxPyk9++9TgREKrazEZ6IhrB/h+MzqIkgkxLuJ6AJwpgxD3EQt
ExQc0I/LCUbhCACM8nK45DrmSDQ5j4cz1M0pqBvGPjW9EAU95c/GsBK8C4YTiBFhCp3MYjwcncXP
CGHI0ioQtDJPDBZAT69i413Bg4KWAIXVQPhKBHw6QMCyFrh0SVR5g4cjeaMROE2QODIfX/wIGrEZ
rCZigEyEAAjHwVETXA5GZpIpBdvQY1D+cJQYXguv4qHp+OFIRhwB74dNhuCDjWxpQ1OEqZX5EFA1
HdlkuaEMQhP4+BVwlMkoiAiMlzf0j2IAtje/jwkOd49NeAM+pjfIjASGx3u7fF2MwxuEvsPJTPSO
+Yd3jjGwIuAdGtvNDHcz3qHdTH/vUJeT8e0aCfiCQWY4wPQOjgz0+mCsd6hzYGdX71AP0wH7hoYh
XPWCJQLQsWEGHyiA6vUFMbBBX6DTD11vR+9A79huJ9PdOzaEYXYDUC8z4g2M9XbuHPAGmJGdgZHh
oA+O7wKwQ71D3QE4xTfoGxpzwakwxvjGocME/d6BAXKUdydgHyD4dQ6P7A709vjHGP/wQJcPBjt8
gJm3Y8DHHwVEdQ54ewedTJd30NvjI7uGAUqALBOwm/D7yBCc54X/Osd6h4cwGZ3DQ2MB6DqBysBY
eutEb9DnZLyB3iBmSHdgGMBjdsKOYQIE9g35eCiY1cwmicAS3N8Z9G3g0uXzDgCsIN6cudgFmVCc
VFUhUs9NU8eQHOqTg1Df/JrUVqm51P16mL83F90pelz0ddE34fu06BnRo/+f34Xlku/l92H/W96H
XX6rcvmtyuW3Kv8T3qrwnvPym5X/nW9WeOldfrty+e3K5bcrl9+ubPXml9+wbH7DkuLO5bcsl9+y
XH7L8j/sLUvGzUOIxIhU/1fQy7yViGy6e+D/1V7mPGQqYrO4Vtwv7hFvg9/mTZBisH8I1h0mOTzv
y+bRY+heEUV8K/7X6QlSJ8MZ/wXFisuzCmVuZHN0cmVhbQplbmRvYmoKMjIgMCBvYmoKMTEwNTQK
ZW5kb2JqCjIwIDAgb2JqCjw8IC9UeXBlIC9Gb250Ci9TdWJ0eXBlIC9DSURGb250VHlwZTIKL0Jh
c2VGb250IC9UaW1lc05ld1JvbWFuUmVndWxhcgovQ0lEU3lzdGVtSW5mbyA8PCAvUmVnaXN0cnkg
KEFkb2JlKSAvT3JkZXJpbmcgKElkZW50aXR5KSAvU3VwcGxlbWVudCAwID4+Ci9Gb250RGVzY3Jp
cHRvciAxOCAwIFIKL0NJRFRvR0lETWFwIC9JZGVudGl0eQovVyBbMCBbNjk3IDI5OCAyNDkgNjk3
IDM5OCA4MjUgNDQ4IDQ0OCAyNDkgMjQ5IDQ0OCAyMjQgMzk4IDQ0OCA0NDggNDQ4IDQ0OCA0NDgg
Mjk4IDQ0OCAyOTggMzQ5IDQ0OCA0NDggNDQ4IDQ0OCA0NDggNjQ3IDQ0OCAyNDkgNjQ3IDQ5OCA1
NDcgMzk4IDY0NyA1NDcgNjQ3IDY0NyA0NDggNjQ3IDU5NyA2NDcgNTQ3IDU5NyA0NDggNjQ3IDQ0
OCA2NDcgNjQ3IDQ0OCA2NDcgODQ1IDQ0OCAyOTggNTk3IDM5OCA0NDggNDQ4IDY0NyAyNDkgMzQ5
IDQ0OCAyNDkgNDk4IDQ0OCBdCl0KPj4KZW5kb2JqCjIxIDAgb2JqCjw8IC9MZW5ndGggODEyID4+
CnN0cmVhbQovQ0lESW5pdCAvUHJvY1NldCBmaW5kcmVzb3VyY2UgYmVnaW4KMTIgZGljdCBiZWdp
bgpiZWdpbmNtYXAKL0NJRFN5c3RlbUluZm8gPDwgL1JlZ2lzdHJ5IChBZG9iZSkgL09yZGVyaW5n
IChVQ1MpIC9TdXBwbGVtZW50IDAgPj4gZGVmCi9DTWFwTmFtZSAvQWRvYmUtSWRlbnRpdHktVUNT
IGRlZgovQ01hcFR5cGUgMiBkZWYKMSBiZWdpbmNvZGVzcGFjZXJhbmdlCjwwMDAwPiA8RkZGRj4K
ZW5kY29kZXNwYWNlcmFuZ2UKMiBiZWdpbmJmcmFuZ2UKPDAwMDA+IDwwMDAwPiA8MDAwMD4KPDAw
MDE+IDwwMDQwPiBbPDAwNzI+IDwwMDY5PiA8MDA2RD4gPDAwNjE+IDwwMDQwPiA8MDA2Rj4gPDAw
NzU+IDwwMDc0PiA8MDA2Qz4gPDAwNkI+IDwwMDJFPiA8MDA2Mz4gPDAwNjc+IDwwMDI0PiA8MDA3
MD4gPDAwNjI+IDwwMDY0PiA8MDA2Nj4gPDAwMzI+IDwwMDJEPiA8MDA3Mz4gPDAwNjg+IDwwMDM1
PiA8MDAzNj4gPDAwMzA+IDwwMDM4PiA8MDA0ND4gPDAwNkU+IDwwMDZBPiA8MDA0OD4gPDAwNTA+
IDwwMDQ1PiA8MDA2NT4gPDAwNTg+IDwwMDRDPiA8MDA3Nz4gPDAwNEI+IDwwMDM5PiA8MDA0RT4g
PDAwNDM+IDwwMDU5PiA8MDA1ND4gPDAwNDI+IDwwMDM3PiA8MDA0Rj4gPDAwMzQ+IDwwMDU2PiA8
MDA1MT4gPDAwNzE+IDwwMDU1PiA8MDA1Nz4gPDAwNzY+IDwwMDQ5PiA8MDA1Mj4gPDAwN0E+IDww
MDc4PiA8MDA3OT4gPDAwNDc+IDwwMDJGPiA8MDA0QT4gPDAwMzE+IDwwMDNBPiA8MDA0Nj4gPDAw
MzM+IF0KZW5kYmZyYW5nZQplbmRjbWFwCkNNYXBOYW1lIGN1cnJlbnRkaWN0IC9DTWFwIGRlZmlu
ZXJlc291cmNlIHBvcAplbmQKZW5kCgplbmRzdHJlYW0KZW5kb2JqCjcgMCBvYmoKPDwgL1R5cGUg
L0ZvbnQKL1N1YnR5cGUgL1R5cGUwCi9CYXNlRm9udCAvVGltZXNOZXdSb21hblJlZ3VsYXIKL0Vu
Y29kaW5nIC9JZGVudGl0eS1ICi9EZXNjZW5kYW50Rm9udHMgWzIwIDAgUl0KL1RvVW5pY29kZSAy
MSAwIFI+PgplbmRvYmoKMjMgMCBvYmoKPDwgL1R5cGUgL0ZvbnREZXNjcmlwdG9yCi9Gb250TmFt
ZSAvUVhBQUFBK1RpbWVzTmV3Um9tYW5Cb2xkCi9GbGFncyA0IAovRm9udEJCb3ggWy01MDMuOTA2
MjUwIC0yOTUuODk4NDM3IDE4MDUuNjY0MDYgOTUzLjEyNTAwMCBdCi9JdGFsaWNBbmdsZSAwIAov
QXNjZW50IDYxMS4zMjgxMjUgCi9EZXNjZW50IC0xOTQuODI0MjE4IAovQ2FwSGVpZ2h0IDAgCi9T
dGVtViA4NS45Mzc1MDAwIAovRm9udEZpbGUyIDI0IDAgUgo+PgplbmRvYmoKMjQgMCBvYmoKPDwK
L0xlbmd0aDEgMTg1ODAgCi9MZW5ndGggMjcgMCBSCi9GaWx0ZXIgL0ZsYXRlRGVjb2RlCj4+CnN0
cmVhbQp4nO15C3Bb13nmPXiSFEkQbxAggHMBigBJEHyAIEiQEgWCIAkJfAgARVFvELgkYYEADICi
FDu2nPhZ2YlTb5pkW2ezSbNONn2lreu+0mTttqudpukmmXon2STTNp466e6Ot+km3Z2I4P7n3IsH
KVl0M7M77YxEXeA/5/7nP////a9zcRnEMEwDc5MRM8xirH/I+Mi5T8LM83Bd2cjcWG8rm04D/d8Z
Rt28ySVS3IfmloD+3zA3sgkTzV9Q/SuG0QzAuHNzq3T9yc/KvgHjOIyfzeSSiZX16BaMvwPjma3E
9TzTxVxhGG0njHE2scV97eK3nobxNMN45hmx+CHRHzJSpkH6r6UehkFH+W/xp5h1kQpJRaIGsVwq
FYklf8W4977CXD8PUhrhYuLzQczA394d6dXyDPLIWfQHJxi0t7cHq1+RRshujJYREWMlL0ueBGvl
DMMqWeVR+ECM+OU7N8XJO3Dnp4+aJSdha8a/97b4tjjC9MBAqdHr9FrWK5PL7DZHl6PLpxyGLy9L
b+g8Q74RYUa8pVKOlj83cexYeM43qtIglcqHzjbK1WqD1dQ5BCNxZPdqwmCQ4YfnWNbVO+5/CS1e
0esb2N2vnDcaW1qV+jn0Bp0gWsztvS16Qcwxx2CgtsPODptcpqW76nVa0IfXyG6T28UeQRUv0QT+
vF2+Ec8QzOlAPVGsFfvGx/1d7UZVx9NP9vQgW+dkYP5YqqPRqra0YufszGSP2WQyXfo55wSanroZ
DBgUbUcadeK18l/dHHCjdgPbrutaXZ08EZkNTnd2djX1of7r/glTu6MXWwOXhsPnriwt2lpRgwwz
jIiZ3ftbcRNo3s4cBd3ZCkx60NgBGnuHYQDKyamydmKVVtxUHpDHjq2OuPqGrKFYPPOlKwuF4idu
Xr70Zlsbq7H2W7zojc9dOWWxLGqe94+jF0u/+s33P4rSVz/y4qjX3OY+fQsTzCCWxO2wM8Qk0o7w
GBCo7DKKCwVNrxVABK8Ci1fJY+ZFn4xPTo4PWi2ow9I9YOuUNjYbDUdVFiQ7otV6yj6fRi1valP1
iiNf/kBvrxWPTthYhM1SCUJqy9jq5usej8LQ3CzCWGI05tA35rSGliNSFrQCFCSPSW4zoySeqEs8
SurQLocQRfykmPVSoqKT3Q5hxjPa0T+2b3uHFSzbbLO7+yGs2nUj4S9sbrhZ30+/1z3MGpqbJEf0
dn+3BLGm/oEVzy3JB8qt6GT4w7uPp6eCeh0qv8Lp9a2taGnxM+VHWKRptuouiLuiGquqnS3/wpPj
Yx1toGuIYaR/CQguVxAkSAlIApZKWRU4n7LqP3klS8j0/hsH+b3o5dD4+Oxpn88yF5yaW/EOa7RI
pRwrRzyGNtTYpNa0Ox3dDoVmonzKplU3yGBOqzV0Wnr7Kdv8sF6BaC7lToGrjjoipzs7nd3HJp8p
/7s1nUEO6HcaVlAmb7UqFB3msbL/gs4mxhgpFTrdSZQpmM3KNrU5WPavdpilGEvN6jX0PT7pRExs
7x/Ej4P1x5kwwxytRutRPq/sMiEBNRDIMj7L+FAmyFBP+oZomNN4UwrsniGR8hcfmRsYiMWRvqm5
w9w5cdRgZBFrGx5zdCGv58LF5PWZGW2LVNLY2GwwmPoGB46ddHQ3ZkfsFl1P36PPof6B2cT8/BPx
KwaDRoXalVqNydHpsmKE7Lb+ExN+bEWeYb/j2fLvjbcq5A2I1U5bLMjOPoNMgbmhwR6rgeRlF/j0
HclbjIKxAUUcK9QQYqO6zodewVVN/m4nQs5uv9/Z3e38Xa3mOKRBh0qrHZe8VZ32A1M5vZs8ZzAS
nLH6PPof5wztEhL5Dtjnf0Lkq+oqaZ385+ol3v7p2zUR4ofOGg0SWgfb996SNoMMoj1SghvkXpYv
f1qlnUr1eUAsqX5KIZO/KrqArC4OfXSx3aRQWO/88cDgcXN5ft3hNDosFp/k9m6jqDXrGEYse0TR
Zu9cuSMV37nz46udXTDT41wTX8EDSoWIWNALu+th93HofKyWxrSMzwK+qEFY8wnqrd3VyA90iy55
r+g6njWZjhxBRoPfdzY5M2O3IdSmau8Jo1fah2321uYOy1buj/7NmZ2BIdQMg3nJbVbR1m5M737+
s8Mjdntf79LCG+gfonZ7q5Zltdpu86ly/3+5cmVpqcd/7twnRCtpo7FNgYifwbvSOdC5l684fIkB
iPbVFi9L45aEgBzx5RCJlbxNXlpx/ltzs9Ua331h2WJpaW5useCYaOy7mxuBEwgljudR15ixc6j8
WHl7yfPY8Ul7Jzox9RGRu/z5FMGcZSHhjO0psTFJ1GKt1mgs+9zKmKmcOK02i1iRW3R29wd63bHx
tVvBIOA8Az3jCGQe9NyjtFHIao2C5puN72y1JkhUFb3TMbG6mvrcOnch98YHFyLIiodGbJ1ymUbb
4bL0dx0NDk73OZzf1uVHRhG6+fhv/coHX0ZTU6eHLRjZO8+NQVl0h168nskOO7RwRmDs5W3xb4MW
3cwI6CG4eV/MstWiKPRgoqiDj4Vhqh56Ch1p0ukmy1Y+sNFaX9/UwoX5iNMJObOwcGVmwj04vzqI
3WjY5r/gP1P+04DB0HQEILOqz4ofobmTO2HpQf7xjY2dmw9d9YHuWPfRrCfyl98+PYyeJFkxCZ3u
a6DpkFCn+Sqk35dkXULRukfmfezEMf9MdGRE3YJUbWPl+IBWgeSNao1+PqhSDZTjwwYFLbJbM1Ba
3O6g56Xya2t6OLpgqV23iq5vdICT0VbZf7m9Xba/iiLGtve/RGckTzBm2u+0dh5HWhr5rPAq7bQj
oBdu34ZDg6qtze81nfzl075RRWP24dOLE5Inyn92dvcnJ7Xalla0qvnVPteo5Vn0n/Di6kqWRHgQ
TmjnwHoleIpBfAHW8Dnng6DR842+Lkt5LNCfb12+NDR4Pvv6H61vonT6D/ox23QEodZG1trjNNmb
VahNyRrE3Jh/I/3ob9/4+aef+o1Xn3nmBLLZ19dfuxIPsKze4ltGso+PjxnVjGjvq+UC+iqtqOO8
HtpKRe2iFVVeN/Tp+EjmWwKfZF6H0seXrKmxbhIeo2PObgSlVqEPTm/lh73IbOyyadQIiRQtBjXk
t6RJjJBKe0zyFjCPO7q7HeOjUH8373zsEf8Zj6evL+CwdMCJROs8olDLsQLcyKp8Ke2bosb+Ma1O
RvxzA2JHIflr3j88SCTIhdyvho3jqOgcOtLIWmY7dh/Bi3D0aIYY0erN7qk29Ibkr+/oH7ZitYZl
VSpsLYnet6zTQkx04K+R+IRTvuzXoQaR0yuqlEZ9/W5CNUJ2oUL5qpP7DkDiAoqgv3eOYH0LeOpI
k8Xqce5+wOllda1N5V5d2S5tdjji5Qstzk6bWtUkamqyWoYd6CfoM+KjrLrVrDt/51uXde1tKrZy
5rn101+WxO98+pzW3WGGei9StBoMPU0xsfSiQQdoVbLrL0D7YYJQ3enn7uw6cPqp5lfI759cHB1T
qclDQbxP38anVxdrd7S2jVQSTHK7rA9bLX3uieMvll+jzwZYZtFfQNfTpvY2RbthsjxxXodphmmv
iM9VzikOiP9XQT8zPekqK2eQWuOR26vH2roHFfp8AI3nqYceP7MQcfX6Rs9f3J4ZHvE8b5XByasP
XZI22m0jfTas1w3aJxZAvf4t5PFcuvjIrXzBP67VDZyXDIWV7S3NInb3e+XnSlYvyxqNC/N/9np4
GPRqhc5jk/wNdCB68hdKtXD+Qx6hz3gr4e9wiMWivXLMa+wxXCmnp3p6JtHvKNHvTXZbR3d/wzBr
1iCJqP3K7/whurgz4fDqFXKWbepzvSD++h3Ni51mCctqFKY2ZcPEd9Bnyhdhf9JFvg24dDLeaufT
a6Ve4cmD1AbBmV6ha6u7hK7No6TziYtSuVbtKf9SYNAz+emL86jfHTt9aWLAPYLkR3TaifcFr9i0
Nq1Wr+/Wdi7OSm7f8SZVllaF2BJ6egEC6sXtLzybuTrqMxj8e1e07S0tXbtvPKEyh2Y/8m8j8zYl
ej+JL8gKibYSX5WO6xDONXK1ABNxGWAk194dXx/9kwnINbXGj9434uy+duFPr+st/eWIpbkFoaOf
G1GpRssRwEupGgUFv/W639RuNLS1NbCsWG8oni9/74s6K5y0jjS1aEd/7P04H3j1IQYP0O+UHxb/
Wvlt8uuAmNWySvGX7wTKb18D7YOg/YdBezvRXng+sd8jtSmydqXkw6zFZj9mXz4P6QvJ2b170+nF
+tam1ff7ljQsBNmrBc+gte3O4v48/eLwyWfQKdivDzQIQr2C/VjWywjnE5vcUTt9Q+Qjlj+PeUTl
3X40PzsD/XP5+Qg7kEp+8ML8vKs3eKH8NdSQsJg1KiurQT/33DMfvDQ5eav5V+JR1Os6dWrq+qOv
lN9saNCoJomPLBBLQ7CrDwbCg80wXxcrMUTSTSjq9rrn2tqjOFJuOJ3mDuTznX78LHtiI/XYY7Eo
cjhOp0d96NatH/zinMdi6bIYW1dXFqYGBlZWRBw2G40g6JR3BD3V/AvzkYWFjdDxyQHPqVOFrzz1
tKdzrBvKe4t8ds47HH1kMw16KsBPz4sj5MQiRbUwgqBRq/kfBIS4EgunFV+XcILR0KYMifl6+Z3j
ZnMPet2lUvV9ZM2r040iY2+76djfX+idvBhx90MJtw70mUyiBplCY7QP2UWFD7G4hRTPNq09Vf4t
hJ4dYTUaEctKTR2f2v3w343MI+TqOTYM1abDPGFvhIPv0WchlkKg7SPQuceZCHOJ1AitvXaUspHT
HWnbHl/tNw5Z5QcNH49wF4+0RyeX7W+mdrFwNvRVyksXPAeYP92r0qFBz/LKlGy922RGcAIf+6Uv
za4jd/986WOFS5cd3Qhbl7cH+jdvjIxwqU/Fg8OdnZ22oZHOTuQ0D3svWDxe70uPzc6hFsPgkHgq
6eocGj4/FTzahaQm01Gs1YqQc3xn4dikxYX0OofD5bSx+rGN4+N+l2tu7vKj584jHxr2fvbZwaGh
wRc/NdF7Z0Vh7u+H9axtQtdmPNJE4k0FNZ340VLnRx6OA35E6Evl73s7tE70lR6FHqHuW7kBrWYY
aboNxqHyD9pFH7qGDZDqCq3Rfr78BlKVhjpUbWKWlRnar+2myV70+sGPXpVdVkz8mPwIePAfnGwe
hv79FvDJqpOwRvJW+WGk1dwEjpuyX6eS6v/ZpJ9EjETC+EX/mQmLvcwsXNOSr8OjtIQJiV9mYiJ4
CoXLIfUx7XD1wmUDnhlYY4drUrQJ45eZadHm3p/D9w3Z15lOMg8XWdMK37NwHRO/vPcOyA0CTx9c
FrgUcM0gOHzANzxvMlrmLPMq8yN0DL0kUomeEP2+6Dtik3gb+rpKsiF5VfK30h7pU9LXZDrZuuw3
ZT+Sz8g/Lv+s/LsNhoZMwxuNS/D3NG8zdLPLpAoKo4P/YuK/g096X2SkM2LKaaEjQouYBtGoQIuZ
qOiEQEsYpygq0FLGIPp5gZYxLtG/F2g5c030pkA3QLdvFehG5mlxRKBbWiXib1R0Qy3KNwUaaoPq
+wItYiSqHwm0mOlW/USgJYxGtSfQUqZZbRVoGaNT9wq0nBlXBwS6gTEovyvQjUxQ/ahAt8hF6i+D
ZCQRk3OA8T8ItIRxG/+C0lKYbzLuCrSE6THJKS2DeZlpUKAlTJfJR2k5wc10UaABKxNH6QaYbza9
INASxmX6BKUbwUiL6U8Emsefp3n8eZrHn6d5/Hmax5+nefx5msefp3n8eZrHn6dbWjXm71O6idje
+48CDba7pJQ+AvMql0egJcyQK0TpZqKba0egQR/X45Ruhfk21ysCLWEGXK9Ruo3KeVugiZz/Q2k1
wbCvV6ABwz4eTw3Rp29FoEGfPh5D8qyr6XtJoCXMcB+/l47y/1eBJvw/pHQ74XfrBRr43fxeJuJT
92WBBp+605Q2U59eFGjiU35fK+V/SaAJ/8uU7iQ+df9HgQafur9J6R6Cj3tPoAGffj5m+oic/n6B
Bjn9Y4RuqMO/oQ7/hjq7Gursaq7jb67jb67zS3PFL59nMDxtDzCDcCLATJzZZDj4nmdyTBauEjxV
5elMEEYFoMlnAubTlMMNdwJMBv4wE4W5DVhfYop0xME3B9zX4DNFOVvgbw5GazDLMTsws0ilZ2Hf
yj4RkH4DZG+DHAxycyAzzSSBTgKdh3uF6j64qv0A4wGqqzryMS6qQwIk5IEXw74J2IfISDJXBd6T
MNqEWXJ3G3QsVm0iOKSpHZl31WedYoGZKRivwR0ym6BI7LeRl5MTLMV0l224m6T2ktE6yN6BtQU6
sw1cKYochvmKP8KgE0EnTddlKbbjdD1HOThmC/YkSKfoJxY0qvBiOl+EGYJfvurBmh3kfgm0SMPK
IqAQB2qLrsHMgmBLFHi3KJJTQGVgzcFI8R+yDldXYsYJq9NUo1wVh27mDLW9WNXPB7oQn9bk8lJr
MpeYGJymaxrFD9WB90mCIkziOUXxIx64Sn21/jPlwt2ctbieprw7wJuFCCKRvw5/aSEK+uCKUfSz
YAMHq/h9C1RTIpXE8xnKXxL8FaH6pqiHSWwOMmOQBUP3wJREyTbokacxwUfHOpVaotG+SiMSUwRu
0AjkI6ZUzYIKN6a7Yyqfo7ZzVLMU5csL2eKi2GbpPnlqA782KUipaJygsvPU31vAVaL3yKo1qkcl
+g9GcklYwedV4a6Z9aoNruq4lkl3o5On4xSsIei6hKwilYvf11Xd56AFaRpNOxSnJK0z98JsR7A0
TStQhtaaSk08iH2ORsANmh1pyIb6zL63dF6HnxXb+rpRic0CzZwS9VyyGt/3sqCy+916jdfFALGE
t6VE96tkToHWmhs0fnKAUpbW18S7WsrHXmJfVPF1Mid88lbxNKnYeaFuE22vVbONl0M4SXe4X4zy
/S0reKYmvZIhaQHlAu0kpA+kBZzdtNtVasg6rU0ZamUF5f1R7aKeSVA6JcTB3fX/YCY4aR8kdvqZ
fvjjaB0ie1ylVZ6jXk3AHEFoAzgq9/oFmZcP9JRuIXtr1aJYRayizT+la7/HLok7DsiIVGRgczWa
H4I53k+VqOHo6SIjdNdadN+v81ei8t27P/HcUjVzinW9iPc3HwWcsNcGjeWs4HcXtbkgdGW+9pDK
kKD4836uxDEfV3mh3/E75EAq34Wz1UhJMLXTz8F69v/AF1WEEtR2gltaqPUpIVeTIH1LyJFaB8S0
o2WEmHFWdHx33zKk6+07/4C3u+swStEuk9lXZ+628T7yaPVN03UV7ntXN9eB6lbB/uDqDD1ZpA/Y
XdGrdjatZU2tE1V86KL1Pkd3Wa+OuboIIXWL91ARpNU6LK/1GtWFEzrVdtWX9bWE92G/4PEizZJM
VYdKXu+PpfeOan2H562s7zT7Y7qGxA7Fcetn9GOlG5Czc1ZAhqvTIEU/yZ41XB4CjmRd7yjdpx7z
lT9FLah0PP++Kp4AiTlace79NMKf/SpdpoZPpZPVMKqvKftXFWmt4H21Jth9756beBePFqrWF4UT
ZYnmb4ZqQO7Xd/SfNQIq/W2OCdG7i8wMjFagW0bpTBjmMFTRKNw5A6NpmJ2GGQdwxIT7DuqpFdqH
5oBvmfY4XkYUPhdgvEpr3AyD6ZiMTgH/Asgia0PMWbpHCKTFKGeUyp6H2Qh8hwQ+siIIM8swJvQs
rYL8fguwin+2Cgs9kdc0DvO4auF+rcJ0x4pm8zCKgvw54W4AZIepPKI/2X+G0gtVPWcETQMUIyKZ
yAyCRhE6IrPL8L0EfDG6f4DazGu7QG2Ygfu8LSGqAdnZLdjK8xF8zgh3iI+IfhH4q1kVoBjMUW1q
+AXhewk0J/Jn4W6cdohFWDlNLY1R9EICZsTaCB3VrOI9FaTWEFQJBtNAz8M1W8UuSj95XaJ10vZj
t0Lv17h4+wLCZ5Ait0hHvDeCdBSnviJ3XYIvo9SOg7uu0EgMUa4AtThWjZAZGr289pXo5PdYrNOE
34/4tl6XSlTj++QIL6Vyf1nw9N24ENQDFBOiV6y687tJdn8eDw0M+nB8k8PzuWyudCPP4WCukM8V
EqV0LuvGgUwGR9Mbm6UijnJFrnCNS7lxS8sct1bgdvBinsvGyZpI4kZuu4QzuY10Eidz+RsFsgYT
8QMe3EW+fC4cTWTym3gukU3mkldh9mRuM4vntlNFslN8M13EmXo567kCnkqvZdLJRAYLOwJPDjbF
xdx2IcnB13ppJ1Hg8HY2xRVwidgRjuNIOslli9w4LnIc5rbWuFSKS+EMP4tTXDFZSOeJgXSPFFdK
pDNFdzy9xRXxAuwSzW0lslO5TKoCiv/APUxuYud8OlnIER26z3CFIpHncw8MUF5gpZxLsT4qKH5Q
AliSwKVCIsVtJQpXcW793b1QnaRYTxcSO+nsBl5cXweDcB+OlRLZDHcD1hbSAKULn0knS2BXJFFI
cdkSHhzzDFU1xcXtfD6TBjjWc9mSG6/mtvFW4gbeBmBKxAVkGpdyOFngEiXOhVPpYh7c4sKJbArn
C2m4mwQWIjhRxHmusJUulUDc2g0KfwXkEtwAXxUqxDrZwUW+qZOq6uQLudR2suTCJLhgrYusqWyQ
zuKdzXRys06zHdg0nU1mtlMkEiva57KZG9iZ7uadXccOEu6nLR8bBM0CVywVADfAu7YBWV6VNU4R
cKZhlxK3RZxTSMOuqdxONpNLpPajl+ChgpgEc3KwFXxul/IQ2ymOmEl4NrlMfj+ikG/ZGwI7cQgI
BHw202tp0Nnd0kIiZD2XyeRoAAhQu/Baogi65rLV+K84wblZKuX9/f1c1r2TvprOc6l0wp0rbPST
UT9wXhYypRvcS8OiSBQjYu6d2vdKyW8IHBHC8U0C80M5sIlAw13jMpCuFO79yU+g3Jf+LS1LxDlF
mkVgN0DAwaqNQgKQSbnwegFSGaInuZkobIDNBGPACjwKy3FuDVI4S0BJ0PJTibP3bgVRKFEs5pLp
BImPVC65vQUeSfBVIp0BZJxE4j5rcUyoP9/sphqlOBCY5v1wTz68ky5tkum6cHMJ4Ua0r9zOpCFO
+b2JrAJfgWEHmkTEQhfeyqXS6+Sbo4Dkt8Gg4iZNWBC9tk2St0gmhSgBC/vB8CIHJR0kEF8LKN1T
VT7hYUs+aQSkqRI7m7mt+9hI0mC7kAVlOCoglYM6TXV5iEuWKgFWi2MI/lSaJp6fD/HEWu4aV9dG
oPqRlKH6kCTL1yJFuFXcTIBVa9y+zE3UGVog2xehUJbS4CJIXj7R7wcAybe5EI4tzsRXAtEQDsfw
UnTxTHg6NI0dgRiMHS68Eo7PLS7HMXBEAwvxVbw4gwMLq/hUeGHahUNnl6KhWAwvRnF4fikSDsFc
eCEYWZ4OL8ziKVi3sAjdKgyZCELji5hsKIgKh2JE2HwoGpyDYWAqHAnHV114JhxfIDJnQGgALwWi
8XBwORKI4qXl6NJiLATbT4PYhfDCTBR2Cc2HFuJu2BXmcOgMDHBsLhCJ0K0Cy6B9lOoXXFxajYZn
5+J4bjEyHYLJqRBoFpiKhPitwKhgJBCed+HpwHxgNkRXLYKUKGUTtFuZC9Ep2C8A/4Px8OICMSO4
uBCPwtAFVkbj1aUr4VjIhQPRcIwAMhNdBPEETlixSIXAuoUQL4VAjfd5BFjIeDkWqukyHQpEQFaM
LK5ndtOf9zfoIwl52Dnsh//93CVmG7XA/A8PXVfjXKcPYYfx81wzdJ/SodwCn/hZ8ZfEfyz+Mnx+
8bA1+3j//77Ea6LXgxd5/1Je5D14IfTghdCDF0L/HF4I8ZXzwUuhf5kvhXjvPXgx9ODF0IMXQw9e
DB2s5g9eDu1/OVRB58ELogcviB68IPpn9oKo+jtI+p/0qwnPTc6GpA5doyevEtSDw9bfvWKWno2K
h66s8M0wP4QadZX5Ccj4Icwd/ovKfv6KnCLD/yKTe88711acodRh63iuOVpTr9HfgQ5fs597iVbW
Aq3SfC0+3EP3WlPvtcPt3cctsUqOS8YlQcmIZFRyQnJMckoydpiEd1nzXn9hq3GeImigQXp2vf+a
Gucp2nfy4PHDLa3jRUrmb8R2uHPImipfRDidHe6RGifD/F81mwgYCmVuZHN0cmVhbQplbmRvYmoK
MjcgMCBvYmoKNzU1OAplbmRvYmoKMjUgMCBvYmoKPDwgL1R5cGUgL0ZvbnQKL1N1YnR5cGUgL0NJ
REZvbnRUeXBlMgovQmFzZUZvbnQgL1RpbWVzTmV3Um9tYW5Cb2xkCi9DSURTeXN0ZW1JbmZvIDw8
IC9SZWdpc3RyeSAoQWRvYmUpIC9PcmRlcmluZyAoSWRlbnRpdHkpIC9TdXBwbGVtZW50IDAgPj4K
L0ZvbnREZXNjcmlwdG9yIDIzIDAgUgovQ0lEVG9HSURNYXAgL0lkZW50aXR5Ci9XIFswIFs2OTcg
NDk4IDM0OSAzOTggMzk4IDU5NyA3NDYgNDQ4IDI0OSAyNDkgNjQ3IDY0NyA2NDcgMzk4IDQ5OCA0
OTggMjk4IDQ0OCAyOTggNDQ4IDg0NSA0OTggNDk4IDY0NyA0OTggNDk4IDQ0OCA1OTcgNDQ4IDQ0
OCA0NDggNDQ4IDIyNCA0NDggXQpdCj4+CmVuZG9iagoyNiAwIG9iago8PCAvTGVuZ3RoIDU5NSA+
PgpzdHJlYW0KL0NJREluaXQgL1Byb2NTZXQgZmluZHJlc291cmNlIGJlZ2luCjEyIGRpY3QgYmVn
aW4KYmVnaW5jbWFwCi9DSURTeXN0ZW1JbmZvIDw8IC9SZWdpc3RyeSAoQWRvYmUpIC9PcmRlcmlu
ZyAoVUNTKSAvU3VwcGxlbWVudCAwID4+IGRlZgovQ01hcE5hbWUgL0Fkb2JlLUlkZW50aXR5LVVD
UyBkZWYKL0NNYXBUeXBlIDIgZGVmCjEgYmVnaW5jb2Rlc3BhY2VyYW5nZQo8MDAwMD4gPEZGRkY+
CmVuZGNvZGVzcGFjZXJhbmdlCjIgYmVnaW5iZnJhbmdlCjwwMDAwPiA8MDAwMD4gPDAwMDA+Cjww
MDAxPiA8MDAyMT4gWzwwMDc1PiA8MDA3Mz4gPDAwNjU+IDwwMDcyPiA8MDA0NT4gPDAwNkQ+IDww
MDYxPiA8MDA2OT4gPDAwNkM+IDwwMDRFPiA8MDA1NT4gPDAwNTI+IDwwMDYzPiA8MDA3MD4gPDAw
NkU+IDwwMDc0PiA8MDA2Rj4gPDAwNkE+IDwwMDMxPiA8MDA0RD4gPDAwNjg+IDwwMDYyPiA8MDA0
MT4gPDAwNjQ+IDwwMDZCPiA8MDA1Rj4gPDAwNTQ+IDwwMDMyPiA8MDAzMz4gPDAwNzk+IDwwMDY3
PiA8MDAyMD4gPDAwNzY+IF0KZW5kYmZyYW5nZQplbmRjbWFwCkNNYXBOYW1lIGN1cnJlbnRkaWN0
IC9DTWFwIGRlZmluZXJlc291cmNlIHBvcAplbmQKZW5kCgplbmRzdHJlYW0KZW5kb2JqCjYgMCBv
YmoKPDwgL1R5cGUgL0ZvbnQKL1N1YnR5cGUgL1R5cGUwCi9CYXNlRm9udCAvVGltZXNOZXdSb21h
bkJvbGQKL0VuY29kaW5nIC9JZGVudGl0eS1ICi9EZXNjZW5kYW50Rm9udHMgWzI1IDAgUl0KL1Rv
VW5pY29kZSAyNiAwIFI+PgplbmRvYmoKMiAwIG9iago8PAovVHlwZSAvUGFnZXMKL0tpZHMgClsK
NSAwIFIKMTIgMCBSCl0KL0NvdW50IDIKL1Byb2NTZXQgWy9QREYgL1RleHQgL0ltYWdlQiAvSW1h
Z2VDXQo+PgplbmRvYmoKeHJlZgowIDI4CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAwOSAw
MDAwMCBuIAowMDAwMDI2NzAwIDAwMDAwIG4gCjAwMDAwMDAxNjMgMDAwMDAgbiAKMDAwMDAwMDI1
OCAwMDAwMCBuIAowMDAwMDAwMjk1IDAwMDAwIG4gCjAwMDAwMjY1NTcgMDAwMDAgbiAKMDAwMDAx
NzQ4MiAwMDAwMCBuIAowMDAwMDAwNjExIDAwMDAwIG4gCjAwMDAwMDMyNzggMDAwMDAgbiAKMDAw
MDAwMDQxNSAwMDAwMCBuIAowMDAwMDAwNTkxIDAwMDAwIG4gCjAwMDAwMDMzNDggMDAwMDAgbiAK
MDAwMDAwMzI5OCAwMDAwMCBuIAowMDAwMDAzNjY2IDAwMDAwIG4gCjAwMDAwMDQ2ODkgMDAwMDAg
biAKMDAwMDAwMzQ3MCAwMDAwMCBuIAowMDAwMDAzNjQ2IDAwMDAwIG4gCjAwMDAwMDQ3MDkgMDAw
MDAgbiAKMDAwMDAwNDk3MCAwMDAwMCBuIAowMDAwMDE2MTM4IDAwMDAwIG4gCjAwMDAwMTY2MTgg
MDAwMDAgbiAKMDAwMDAxNjExNiAwMDAwMCBuIAowMDAwMDE3NjI4IDAwMDAwIG4gCjAwMDAwMTc4
ODYgMDAwMDAgbiAKMDAwMDAyNTU1NyAwMDAwMCBuIAowMDAwMDI1OTEwIDAwMDAwIG4gCjAwMDAw
MjU1MzYgMDAwMDAgbiAKdHJhaWxlcgo8PAovU2l6ZSAyOAovSW5mbyAxIDAgUgovUm9vdCAxMyAw
IFIKPj4Kc3RhcnR4cmVmCjI2ODA1CiUlRU9GCg==

--===============3443409471449293251==--
